### ISSUE TITLE
Error trying to grab the activities of a specific assay

### ISSUE THREAD

**Issue by bjonnh** [chembl/chembl_webresource_client#10]
new_client.activity.filter(assay_chembl_id='CHEMBL730848')

I get: 

TypeError: 'NoneType' object cannot be interpreted as an integer

In: chembl_webresource_client/query_set.py in __len__(self)

**Comment by bjonnh** [comment]
Seems that now it is working, is there a way to invalidate the cache when bad data has been saved in it?

**Comment by mnowotka** [comment]
Yes, if you are using the latest version of the client invalidating cache should be done this way:

    rm ~/.chembl_ws_client__development.sqlite

in the older versions cache is kept in the current directory so you should do:

    rm chembl_ws_client__development.sqlite

Anyway, None and errors shouldn't be kept in cache so I'll look into that.

**Comment by bjonnh** [comment]
That was quick, thanks :)

**Comment by mnowotka** [comment]
Sorry, instead of `development`, there should be actual version number so in order to clean cache you should use:

    rm ~/.chembl_ws_client_*.sqlite
