### ISSUE TITLE
get target image & smiles 

### ISSUE THREAD

**Issue by shahik** [chembl/chembl_webresource_client#102]
Hi, 
    thanks for the awesome repo. How can I get a specific target structure & smiles for docking purposes? 
I tried, 
https://www.ebi.ac.uk/chembl/api/data/image/CHEMBL1914272

`from chembl_webresource_client.new_client import new_client
image = new_client.image
image.get('CHEMBL1914272')`
`from chembl_webresource_client.new_client import new_client
molecule = new_client.molecule
m1 = molecule.get('CHEMBL1914272')
m1`

error: (Caused by ResponseError('too many 404 error responses'))
kindly let me know the solutions?

**Comment by eloyfelix** [comment]
ChEMBL is a compound database. To retrieve structures (pdb files) PDBe would be the place to go: https://www.ebi.ac.uk/pdbe/node/1
