### ISSUE TITLE
Target Predictions

### ISSUE THREAD

**Issue by Agbeli** [chembl/chembl_webresource_client#103]
Hello all, 

Thank you very much for making this framework available for all. Please can someone share with me the code for getting the target predictions for a given compound on Chembl platform. Thank you for your assistance.

**Comment by eloyfelix** [comment]
Hi,

To compute target predictions using ChEMBL made models you could either use:

https://github.com/chembl/of_conformal
or
https://github.com/chembl/chembl_multitask_model

**Comment by Anju321** [comment]
> Hi,
> 
> To compute target predictions using ChEMBL made models you could either use:
> 
> https://github.com/chembl/of_conformal or https://github.com/chembl/chembl_multitask_model

Is there a python code in chembl_webresource_client to find the target predictions for a small molecule?
