### ISSUE TITLE
HttpApplicationError when downloading data from chembl document

### ISSUE THREAD

**Issue by itssahil** [chembl/chembl_webresource_client#108]
I am trying to download data from the ChEMBL database with the simple code below and getting the following error when I try to download data for "Bioorg. Med. Chem."

Code:
from chembl_webresource_client.new_client import new_client
document = new_client.document
docs = document.filter(journal="Bioorg. Med. Chem.").only('document_chembl_id')
compound_record = new_client.compound_record
records = compound_record.filter(document_chembl_id__in=[doc['document_chembl_id'] for doc in docs]).only(['document_chembl_id', 'molecule_chembl_id'])
records

Error:
HttpApplicationError                      Traceback (most recent call last)
/cluster/app/Python/3.7.2/lib/python3.7/site-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/cluster/app/Python/3.7.2/lib/python3.7/site-packages/IPython/lib/pretty.py in pretty(self, obj)
    400                         if cls is not object \
    401                                 and callable(cls.__dict__.get('__repr__')):
--> 402                             return _repr_pprint(obj, self, cycle)
    403 
    404             return _default_pprint(obj, self, cycle)

/cluster/app/Python/3.7.2/lib/python3.7/site-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    695     """A pprint that just redirects to the normal repr function."""
    696     # Find newlines and replace them with p.break_()
--> 697     output = repr(obj)
    698     for idx,output_line in enumerate(output.splitlines()):
    699         if idx:

~/.local/lib/python3.7/site-packages/chembl_webresource_client/query_set.py in __repr__(self)
     76             return '{0} resource'.format(self.model.name)
     77         clone = self._clone()
---> 78         data = list(clone[:Settings.Instance().REPR_OUTPUT_SIZE])
     79         length = len(self)
     80         if length > Settings.Instance().REPR_OUTPUT_SIZE:

~/.local/lib/python3.7/site-packages/chembl_webresource_client/query_set.py in __next__(self)
    125 
    126     def __next__(self):
--> 127         return self.next()
    128 
    129 #-----------------------------------------------------------------------------------------------------------------------

~/.local/lib/python3.7/site-packages/chembl_webresource_client/query_set.py in next(self)
    111             return None
    112         if not self.chunk and not self.current_index:
--> 113             self.chunk = self.query.get_page()
    114         if not self.chunk or self.current_index >= len(self.chunk):
    115             self.chunk = self.query.next_page()

~/.local/lib/python3.7/site-packages/chembl_webresource_client/url_query.py in get_page(self)
    392             self.logger.info('From cache: {0}'.format(res.from_cache if hasattr(res, 'from_cache') else False))
    393             if not res.ok:
--> 394                 handle_http_error(res)
    395             if self.frmt == 'json':
    396                 json_data = res.json()

~/.local/lib/python3.7/site-packages/chembl_webresource_client/http_errors.py in handle_http_error(request)
    111         exception_class = status_to_exception.get(request.status_code, BaseHttpException)
    112         if request.text:
--> 113             raise exception_class(request.url, request.text)
    114         raise exception_class(request.url, request.content)
    115 

HttpApplicationError: Error for url https://www.ebi.ac.uk/chembl/api/data/compound_record.json, server response: <!doctype html>

 <html class="no-js" lang="en"> 
<head>
    <meta charset="utf-8">

    
     

    <title>Server error &lt; EMBL-EBI</title>
    <meta name="description" content="EMBL-EBI">
    <meta name="keywords" content="bioinformatics, europe, institute">
    <meta name="author" content="EMBL-EBI">

    
    <meta name="viewport" content="width=device-width,initial-scale=1">

    

    
    
    <link rel="stylesheet" href="//www.ebi.ac.uk/web_guidelines/css/compliance/develop/boilerplate-style.css">
    <link rel="stylesheet" href="//www.ebi.ac.uk/web_guidelines/css/compliance/develop/ebi-global.css" type="text/css" media="screen">
    <link rel="stylesheet" href="//www.ebi.ac.uk/web_guidelines/css/compliance/develop/ebi-visual.css" type="text/css" media="screen">
    <link rel="stylesheet" href="//www.ebi.ac.uk/web_guidelines/css/compliance/develop/984-24-col-fluid.css" type="text/css" media="screen">

    
    
    <link rel="stylesheet" href="//www.ebi.ac.uk/web_guidelines/css/compliance/develop/embl-petrol-colours.css" type="text/css" media="screen">

    
    

    
    

        
    

    
    

    
    <script src="//www.ebi.ac.uk/web_guidelines/js/libs/modernizr.custom.49274.js"></script>

</head>

<body class="level1 page-error">
<div id="skip-to">
    <ul>
        <li><a href="#content">Skip to main content</a></li>
        <li><a href="#local-nav">Skip to local navigation</a></li>
        <li><a href="#global-nav">Skip to EBI global navigation menu</a></li>
        <li><a href="#global-nav-expanded">Skip to expanded EBI global navigation menu (includes all sub-sections)</a></li>
    </ul>
</div>

<div id="wrapper" class="container_24">
    <header>
                                <div id="global-masthead" class="masthead grid_24">
            
            <a href="//www.ebi.ac.uk/" title="Go to the EMBL-EBI homepage"><img src="//www.ebi.ac.uk/web_guidelines/images/logos/EMBL-EBI/EMBL_EBI_Logo_white.png" alt="EMBL European Bioinformatics Institute"></a>

            <nav>
                <ul id="global-nav">
                    
                                        <li id="services" class=" first "><a href="//www.ebi.ac.uk/services" title="Services">Services</a></li>
                                        <li id="research" class=""><a href="//www.ebi.ac.uk/research" title="Research">Research</a></li>
                                        <li id="training" class=""><a href="//www.ebi.ac.uk/training" title="Training">Training</a></li>
                                        <li id="industry" class=""><a href="//www.ebi.ac.uk/industry" title="Industry">Industry</a></li>
                                        <li id="about" class=" last"><a href="//www.ebi.ac.uk/about" title="About us">About us</a></li>
                                    </ul>
            </nav>

        </div>
                                <div id="local-masthead" class="masthead grid_24 nomenu">

            
            

        <div class="" id="local-title">
                                                                    <h1><a href="/" title="Back to Server error homepage">Server error</a></h1>
                                            </div>

        

        
        

</div>
</header>

<div id="content" role="main" class="grid_24 clearfix">
        
    <section>
        <section class="grid_24">
          			                        										
              
    
  <div class="content">
    <div>

  
      
  
  <div class="content">
    <div>
    <div>
          <div>
<h2 class="alert">Something has gone wrong with our web server</h2>
<p>Our web server says this is a <span class="alert">500 internal server error</span>: the request cannot be carried out by the server.<br />
This problem means that the service you are trying to access is currently unavailable. We're very sorry.</p>
<p>Please try again but if it keeps happening, you can <a fix="h-" href="//www.ebi.ac.uk/support">contact us</a> and we will try to help you.</p>
</div>
      </div>
</div>
  </div>

  
  
</div>
  </div>

    
  <div class="content">
    <form id="ebi_search" action="/ebisearch/search.ebi">
  <fieldset><legend><span>Explore the EBI:</span></legend>
    <input id="query" title="EB-eye Search" tabindex="1" type="text" name="query" value="" size="35" maxlength="2048" style="width: 80%" /><input id="search_submit" class="submit" tabindex="2" type="submit" value="Search" name="submit" /><input id="allebi" type="hidden" name="db" value="allebi" checked="checked" /><input type="hidden" name="requestFrom" value="ebi_error" /><div>
     <p id="example">Examples: <a href="/ebisearch/search.ebi?db=allebi&amp;requestFrom=ebi_error&amp;query=blast">blast</a>, <a href="/ebisearch/search.ebi?db=allebi&amp;query=keratin&amp;requestFrom=ebi_error">keratin</a>, <a href="/ebisearch/search.ebi?db=allebi&amp;query=bfl1&amp;requestFrom=ebi_error">bfl1</a>...</p>
    </div>
  </fieldset></form>  </div>

										
      										
		</section>    </section>

        

</div>

<footer>

    
        
        
        
    <div id="global-footer" class="grid_24">

        <nav id="global-nav-expanded">

            <div class="grid_4 alpha">
                <h3 class="embl-ebi"><a href="//www.ebi.ac.uk/" title="EMBL-EBI">EMBL-EBI</a></h3>
            </div>

            <div class="grid_4">
                <h3 class="services"><a href="//www.ebi.ac.uk/services">Services</a></h3>
            </div>

            <div class="grid_4">
                <h3 class="research"><a href="//www.ebi.ac.uk/research">Research</a></h3>
            </div>

            <div class="grid_4">
                <h3 class="training"><a href="//www.ebi.ac.uk/training">Training</a></h3>
            </div>

            <div class="grid_4">
                <h3 class="industry"><a href="//www.ebi.ac.uk/industry">Industry</a></h3>
            </div>

            <div class="grid_4 omega">
                <h3 class="about"><a href="//www.ebi.ac.uk/about">About us</a></h3>
            </div>

        </nav>

        <section id="ebi-footer-meta">
            <p class="address">EMBL-EBI, Wellcome Trust Genome Campus, Hinxton, Cambridgeshire, CB10 1SD, UK &nbsp; &nbsp; +44 (0)1223 49 44 44</p>
            <p class="legal">Copyright &copy; EMBL-EBI 2013 | EBI is an Outstation of the <a href="http://www.embl.org">European Molecular Biology Laboratory</a> | <a href="/about/privacy">Privacy</a> | <a href="/about/cookies">Cookies</a> | <a href="/about/terms-of-use">Terms of use</a></p>
        </section>

    </div>
        
</footer>
</div> 

<script defer="defer" src="//www.ebi.ac.uk/web_guidelines/js/cookiebanner.js"></script>
<script defer="defer" src="//www.ebi.ac.uk/web_guidelines/js/foot.js"></script>

</body>
</html>

**Comment by eloyfelix** [comment]
sorry for the delayed reply. It seems the server is timing out because is a pretty big query (>6000 document ids). I would recommend sending smaller batches in the second query.

```python
from chembl_webresource_client.new_client import new_client
document = new_client.document
docs = document.filter(journal="Bioorg. Med. Chem.").only('document_chembl_id')
compound_record = new_client.compound_record
doc_ids = [doc['document_chembl_id'] for doc in docs]

# send only 1000
records = compound_record.filter(document_chembl_id__in=doc_ids[0:1000]).only(['document_chembl_id', 'molecule_chembl_id'])
records
```
