### ISSUE TITLE
Problem in getting  bioactivity data for specific ChEMBL molecules

### ISSUE THREAD

**Issue by mahendra-awale** [chembl/chembl_webresource_client#11]
Hello,
 
I am using python connect to collect all bioactivity data from ChEMBL. I am trying to collect activity data for each of the ~1.5 millions compound using compound ChEMBL ID as query.  I managed to get  data for more then 1 million compounds, however the python connect returning  error 500 for specific list of molecules. There are more than 80 thousands compounds for which this error is reproducible. Some of the molecules ID listed here: CHEMBL1090938, CHEMBL1094414, CHEMBL1094415...

This is the line which throws error 500.

activity = compounds.bioactivities('CHEMBL1090938', frmt='json')

Any suggetions or help will be greatly appreciated!

Thanks

**Comment by mnowotka** [comment]
Hi,

I confirm I can reproduce this error. As a quick workaround I'd suggest to use the "new" client, code below:

    from chembl_webresource_client.new_client import new_client
    activity = new_client.activity
    res = activity.filter(molecule_chembl_id="CHEMBL1090938")
    print res

Although the "old" client is obsolete it's still maintained and should work so I'll definitely look into that.

**Comment by mahendra-awale** [comment]
Thanks for your prompt reply and provided alternative solution.

Regards
Mahendra

**Comment by mnowotka** [comment]
Hi,

Can you update the client (`pip install chembl_webresource_client -U`), try again and tell me if the problem is solved now?

**Comment by bjonnh** [comment]
using the last version (with python3), I tried to delete the cache as it helped me in another issue, but it didn't in that case:
from chembl_webresource_client.new_client import new_client
activity = new_client.activity
res = activity.filter(molecule_chembl_id="CHEMBL1090938")
print(res)


---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-309ddbcda60c> in <module>()
      1 activity = new_client.activity
      2 res = activity.filter(molecule_chembl_id="CHEMBL1090938")
----> 3 print(res)

/home/jo/anaconda3/lib/python3.5/site-packages/chembl_webresource_client/query_set.py in __repr__(self)
     78         clone = self._clone()
     79         data = list(clone[:Settings.Instance().REPR_OUTPUT_SIZE])
---> 80         length = len(self)
     81         if length > Settings.Instance().REPR_OUTPUT_SIZE:
     82             data[-1] = "...(remaining elements truncated)..."

/home/jo/anaconda3/lib/python3.5/site-packages/chembl_webresource_client/query_set.py in __len__(self)
     96         if not self.can_filter:
     97             return 1
---> 98         return len(self.query)
     99 
    100 #-----------------------------------------------------------------------------------------------------------------------

TypeError: 'NoneType' object cannot be interpreted as an integer

**Comment by mnowotka** [comment]
Hi, 
Thanks for reporting this. I created a fresh environment with Python 3.5:

    conda create -q -n client3 python=3.5
    source activate client3

And installed the client:

    pip install chembl_webresource_client
    > Collecting chembl-webresource-client
    > Downloading chembl_webresource_client-0.8.36.tar.gz

Now I tried your code:

    $ python
    Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:24:55) 
    [GCC 4.2.1 (Apple Inc. build 5577)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from chembl_webresource_client.new_client import new_client
    >>> activity = new_client.activity
    >>> res = activity.filter(molecule_chembl_id="CHEMBL1090938")
    >>> print(res)

And I got valid results:

    [{'target_organism': 'Mus musculus', 'potential_duplicate': False, 'standard_value': '10000', 'assay_chembl_id': 'CHEMBL1104421', 'standard_type': 'Ki', 'standard_units': 'nM', 'target_chembl_id': 'CHEMBL2181', 'document_journal': 'Bioorg. Med. Chem. Lett.', 'standard_flag': True, 'standard_relation': '>', 'document_chembl_id': 'CHEMBL1156219', 'molecule_chembl_id': 'CHEMBL1090938', 'published_value': '10000', 'uo_units': 'UO_0000065', 'qudt_units': 'http://www.openphacts.org/units/Nanomolar', 'data_validity_comment': None, 'record_id': 905226, 'activity_comment': None, 'document_year': 2010, 'pchembl_value': None, 'published_relation': '>', 'bao_endpoint': 'BAO_0000192', 'canonical_smiles': 'CN(C)Cc1ccc(CCC(=O)NS(=O)(=O)c2ccc(F)c(F)c2)c(OCCc3ccc4ccccc4c3)c1', 'published_units': 'nM', 'assay_description': 'Displacement of [3H]PGE2 from mouse EP1 receptor expressed in CHO cells after 60 mins by scintillation counter', 'target_pref_name': 'Prostanoid EP1 receptor', 'bao_format': 'BAO_0000219', 'activity_id': 3235364, 'assay_type': 'B', 'published_type': 'Ki'}, {'target_organism': 'Rattus norvegicus', 'potential_duplicate': False, 'standard_value': '32', 'assay_chembl_id': 'CHEMBL1104424', 'standard_type': 'Inhibition', 'standard_units': '%', 'target_chembl_id': 'CHEMBL376', 'document_journal': 'Bioorg. Med. Chem. Lett.', 'standard_flag': True, 'standard_relation': '=', 'document_chembl_id': 'CHEMBL1156219', 'molecule_chembl_id': 'CHEMBL1090938', 'published_value': '32', 'uo_units': 'UO_0000187', 'qudt_units': 'http://qudt.org/vocab/unit#Percent', 'data_validity_comment': None, 'record_id': 905226, 'activity_comment': None, 'document_year': 2010, 'pchembl_value': None, 'published_relation': '=', 'bao_endpoint': 'BAO_0000201', 'canonical_smiles': 'CN(C)Cc1ccc(CCC(=O)NS(=O)(=O)c2ccc(F)c(F)c2)c(OCCc3ccc4ccccc4c3)c1', 'published_units': '%', 'assay_description': 'Inhibition of PGE2-induced uterine contraction in pregnant rat at 1 mg/kg, id', 'target_pref_name': 'Rattus norvegicus', 'bao_format': 'BAO_0000218', 'activity_id': 3235394, 'assay_type': 'F', 'published_type': 'INH'}, {'target_organism': 'Mus musculus', 'potential_duplicate': False, 'standard_value': '8.2', 'assay_chembl_id': 'CHEMBL1104418', 'standard_type': 'Ki', 'standard_units': 'nM', 'target_chembl_id': 'CHEMBL4336', 'document_journal': 'Bioorg. Med. Chem. Lett.', 'standard_flag': True, 'standard_relation': '=', 'document_chembl_id': 'CHEMBL1156219', 'molecule_chembl_id': 'CHEMBL1090938', 'published_value': '8.2', 'uo_units': 'UO_0000065', 'qudt_units': 'http://www.openphacts.org/units/Nanomolar', 'data_validity_comment': None, 'record_id': 905226, 'activity_comment': None, 'document_year': 2010, 'pchembl_value': '8.09', 'published_relation': '=', 'bao_endpoint': 'BAO_0000192', 'canonical_smiles': 'CN(C)Cc1ccc(CCC(=O)NS(=O)(=O)c2ccc(F)c(F)c2)c(OCCc3ccc4ccccc4c3)c1', 'published_units': 'nM', 'assay_description': 'Displacement of [3H]PGE2 from mouse EP3 receptor expressed in CHO cells after 60 mins by scintillation counter', 'target_pref_name': 'Prostanoid EP3 receptor', 'bao_format': 'BAO_0000219', 'activity_id': 3235321, 'assay_type': 'B', 'published_type': 'Ki'}, {'target_organism': 'Mus musculus', 'potential_duplicate': False, 'standard_value': '24', 'assay_chembl_id': 'CHEMBL1104419', 'standard_type': 'IC50', 'standard_units': 'nM', 'target_chembl_id': 'CHEMBL4336', 'document_journal': 'Bioorg. Med. Chem. Lett.', 'standard_flag': True, 'standard_relation': '=', 'document_chembl_id': 'CHEMBL1156219', 'molecule_chembl_id': 'CHEMBL1090938', 'published_value': '24', 'uo_units': 'UO_0000065', 'qudt_units': 'http://www.openphacts.org/units/Nanomolar', 'data_validity_comment': None, 'record_id': 905226, 'activity_comment': None, 'document_year': 2010, 'pchembl_value': '7.62', 'published_relation': '=', 'bao_endpoint': 'BAO_0000190', 'canonical_smiles': 'CN(C)Cc1ccc(CCC(=O)NS(=O)(=O)c2ccc(F)c(F)c2)c(OCCc3ccc4ccccc4c3)c1', 'published_units': 'nM', 'assay_description': 'Antagonist activity at mouse EP3 receptor expressed in CHO cells assessed as inhibition of PGE2-induced increase in intracellular calcium level after 1 hr by FDSS in presence of 1% bovine serum albumin', 'target_pref_name': 'Prostanoid EP3 receptor', 'bao_format': 'BAO_0000219', 'activity_id': 3235344, 'assay_type': 'F', 'published_type': 'IC50'}, '...(remaining elements truncated)...']

Can you check your internet connection?
Under the hood, the client tries to access this URL: https://www.ebi.ac.uk/chembl/api/data/activity?molecule_chembl_id=CHEMBL1090938, can you check if you can access it from your web browser or `curl` it?

Because the client retrieves data through HTTP, which can always fail, I think you should add some error handling in your code in case no data is returned. You can also tweak some changes in the client settings (https://github.com/chembl/chembl_webresource_client/blob/master/chembl_webresource_client/settings.py) to get behavior, that is better suited to your network settings.

**Comment by bjonnh** [comment]
Well now it works, I'm really surprised. 

Writing my own function using requests worked perfectly so I could access the URL for sure (also I was accessing other data from the new_client before and after and it worked). But I couldn't get the client to work with the activity filter with molecule id at all.

Restarting the pyhon kernel (jupyter) solved the issue. I'm wondering if there is some state saved somewhere (I deleted the sqlite, it changed nothing), and something just got stuck…

As it is not the first time it happens, I'll try to investigate that further next time…

**Comment by mnowotka** [comment]
Yes, I would appreciate any hints. In general the client is just a wrapper around requests (plus caching, asynchronous requests and lots of syntactic sugar for handling pagination and filtering). I'll add some more checks in code to make sure that `self.query` is not `None` and try to think about cases when this can happen.

**Comment by BJWiley233** [comment]
Can you add a up to the main markdown instructions for updating with new package 0.10.3.  The 0.10.1 from conda is what is causng this issue.
