### ISSUE TITLE
Error for url https://www.ebi.ac.uk/chembl/api/data/activity.json, server response: <!doctype html>

### ISSUE THREAD

**Issue by FelPVic** [chembl/chembl_webresource_client#116]
Grettings
I will try to extract some activities and pass to dataframe with this code:

          ` ### Conect with ChEMBL API            
            activity =  new_client.activity
            target = new_client.target
            listOfActivities = activity.filter(target_chembl_id=id).filter(
                    standard_type="IC50").filter(standard_units="nM").only(
                        "canonical_smiles", "molecule_chembl_id", "pchembl_value", 
                        "standard_units", "standard_value"
                    )
            if not listOfActivities:
                print("Error in ChEMBL ID")
            else:
                targetInfo = target.filter(target_chembl_id=id).only(
                    "pref_name", "target_type"
                    )
                targetData = pd.DataFrame(targetInfo)
                targetName = targetData["pref_name"][0]
                targetData["activities_founded"] = len(listOfActivities)
              ### Do a dataframe and calculate pIC50
              dfActivities = pd.DataFrame(listOfActivities)`

But the script returns this error in some ocations:

      `File "/nfs/home/dvictori/Documents/chembl/chembl_activites.py", line 50, in <module>
          dfActivities = pd.DataFrame(listOfActivities)
        File "/nfs/home/dvictori/anaconda3/envs/rdkit/lib/python3.9/site-packages/pandas/core/frame.py", line 710, in __init__
          data = list(data)
        File "/nfs/home/dvictori/anaconda3/envs/rdkit/lib/python3.9/site-packages/chembl_webresource_client/query_set.py", line 127, in __next__
          return self.next()
        File "/nfs/home/dvictori/anaconda3/envs/rdkit/lib/python3.9/site-packages/chembl_webresource_client/query_set.py", line 115, in next
          self.chunk = self.query.next_page()
        File "/nfs/home/dvictori/anaconda3/envs/rdkit/lib/python3.9/site-packages/chembl_webresource_client/url_query.py", line 434, in next_page
          return self.get_page()
        File "/nfs/home/dvictori/anaconda3/envs/rdkit/lib/python3.9/site-packages/chembl_webresource_client/url_query.py", line 394, in get_page
          handle_http_error(res)
        File "/nfs/home/dvictori/anaconda3/envs/rdkit/lib/python3.9/site-packages/chembl_webresource_client/http_errors.py", line 113, in handle_http_error
          raise exception_class(request.url, request.text)
      chembl_webresource_client.http_errors.HttpApplicationError: Error for url https://www.ebi.ac.uk/chembl/api/data/activity.json, server response: <!doctype html>
      
      
      
      
      
       <html class="no-js" lang="en"> 
      <head>
          <meta charset="utf-8">

    
     

    <title>Server error &lt; EMBL-EBI</title>
    <meta name="description" content="EMBL-EBI">
    <meta name="keywords" content="bioinformatics, europe, institute">
    <meta name="author" content="EMBL-EBI">

    
    <meta name="viewport" content="width=device-width,initial-scale=1">

    

    
    
    <link rel="stylesheet" href="//www.ebi.ac.uk/web_guidelines/css/compliance/develop/boilerplate-style.css">
    <link rel="stylesheet" href="//www.ebi.ac.uk/web_guidelines/css/compliance/develop/ebi-global.css" type="text/css" media="screen">
    <link rel="stylesheet" href="//www.ebi.ac.uk/web_guidelines/css/compliance/develop/ebi-visual.css" type="text/css" media="screen">
    <link rel="stylesheet" href="//www.ebi.ac.uk/web_guidelines/css/compliance/develop/984-24-col-fluid.css" type="text/css" media="screen">

    
    
    <link rel="stylesheet" href="//www.ebi.ac.uk/web_guidelines/css/compliance/develop/embl-petrol-colours.css" type="text/css" media="screen">

    
    

    
    

        
    

    
    

    
    <script src="//www.ebi.ac.uk/web_guidelines/js/libs/modernizr.custom.49274.js"></script>

          </head>
          
          <body class="level1 page-error">
          <div id="skip-to">
              <ul>
                  <li><a href="#content">Skip to main content</a></li>
                  <li><a href="#local-nav">Skip to local navigation</a></li>
                  <li><a href="#global-nav">Skip to EBI global navigation menu</a></li>
                  <li><a href="#global-nav-expanded">Skip to expanded EBI global navigation menu (includes all sub-sections)</a></li>
              </ul>
          </div>
      
      <div id="wrapper" class="container_24">
          <header>
                                      <div id="global-masthead" class="masthead grid_24">
                  
                  <a href="//www.ebi.ac.uk/" title="Go to the EMBL-EBI homepage"><img src="//www.ebi.ac.uk/web_guidelines/images/logos/EMBL-EBI/EMBL_EBI_Logo_white.png" alt="EMBL European Bioinformatics Institute"></a>
  
              <nav>
                  <ul id="global-nav">
                      
                                          <li id="services" class=" first "><a href="//www.ebi.ac.uk/services" title="Services">Services</a></li>
                                          <li id="research" class=""><a href="//www.ebi.ac.uk/research" title="Research">Research</a></li>
                                          <li id="training" class=""><a href="//www.ebi.ac.uk/training" title="Training">Training</a></li>
                                          <li id="industry" class=""><a href="//www.ebi.ac.uk/industry" title="Industry">Industry</a></li>
                                          <li id="about" class=" last"><a href="//www.ebi.ac.uk/about" title="About us">About us</a></li>
                                      </ul>
              </nav>
  
          </div>
                                  <div id="local-masthead" class="masthead grid_24 nomenu">
  
              
              
  
          <div class="" id="local-title">
                                                                      <h1><a href="/" title="Back to Server error homepage">Server error</a></h1>
                                              </div>
  
          
  
          
          
  
    </div>
    </header>
    
    <div id="content" role="main" class="grid_24 clearfix">
            
        <section>
            <section class="grid_24">
                                                          
                
      
    <div class="content">
      <div>
  
    
        
    
    <div class="content">
      <div>
      <div>
            <div>
          <h2 class="alert">Something has gone wrong with our web server</h2>
          <p>Our web server says this is a <span class="alert">500 internal server error</span>: the request cannot be carried out by the server.<br />
          This problem means that the service you are trying to access is currently unavailable. We're very sorry.</p>
          <p>Please try again but if it keeps happening, you can <a fix="h-" href="//www.ebi.ac.uk/support">contact us</a> and we will try to help you.</p>
          </div>
                </div>
          </div>
            </div>
          
            
            
          </div>
            </div>
  
  
      
      <div class="content">
        <form id="ebi_search" action="/ebisearch/search.ebi">
      <fieldset><legend><span>Explore the EBI:</span></legend>
        <input id="query" title="EB-eye Search" tabindex="1" type="text" name="query" value="" size="35" maxlength="2048" style="width: 80%" /><input id="search_submit" class="submit" tabindex="2" type="submit" value="Search" name="submit" /><input id="allebi" type="hidden" name="db" value="allebi" checked="checked" /><input type="hidden" name="requestFrom" value="ebi_error" /><div>
         <p id="example">Examples: <a href="/ebisearch/search.ebi?db=allebi&amp;requestFrom=ebi_error&amp;query=blast">blast</a>, <a href="/ebisearch/search.ebi?db=allebi&amp;query=keratin&amp;requestFrom=ebi_error">keratin</a>, <a href="/ebisearch/search.ebi?db=allebi&amp;query=bfl1&amp;requestFrom=ebi_error">bfl1</a>...</p>
        </div>
      </fieldset></form>  </div>
  
  
        
                  </section>    </section>
  
          
            
            </div>
            
            <footer>
  
      
          
          
          
      <div id="global-footer" class="grid_24">
  
          <nav id="global-nav-expanded">
  
              <div class="grid_4 alpha">
                  <h3 class="embl-ebi"><a href="//www.ebi.ac.uk/" title="EMBL-EBI">EMBL-EBI</a></h3>
              </div>
  
              <div class="grid_4">
                  <h3 class="services"><a href="//www.ebi.ac.uk/services">Services</a></h3>
              </div>
  
              <div class="grid_4">
                  <h3 class="research"><a href="//www.ebi.ac.uk/research">Research</a></h3>
              </div>
  
              <div class="grid_4">
                  <h3 class="training"><a href="//www.ebi.ac.uk/training">Training</a></h3>
              </div>
  
              <div class="grid_4">
                  <h3 class="industry"><a href="//www.ebi.ac.uk/industry">Industry</a></h3>
              </div>
  
              <div class="grid_4 omega">
                  <h3 class="about"><a href="//www.ebi.ac.uk/about">About us</a></h3>
              </div>
  
          </nav>
  
          <section id="ebi-footer-meta">
                        <p class="address">EMBL-EBI, Wellcome Trust Genome Campus, Hinxton, Cambridgeshire, CB10 1SD, UK &nbsp; &nbsp; +44 (0)1223 49 44 44</p>
                        <p class="legal">Copyright &copy; EMBL-EBI 2013 | EBI is an Outstation of the <a href="http://www.embl.org">European Molecular Biology Laboratory</a> | <a href="/about/privacy">Privacy</a> | <a href="/about/cookies">Cookies</a> | <a href="/about/terms-of-use">Terms of use</a></p>
                    </section>
            
                </div>
                    
            </footer>
            </div> 
            
            
            
            
            
            
            
            
            
            <script defer="defer" src="//www.ebi.ac.uk/web_guidelines/js/cookiebanner.js"></script>
            <script defer="defer" src="//www.ebi.ac.uk/web_guidelines/js/foot.js"></script>
            
            
            
            
            
            
            
            
            
            
            
            </body>
            </html>
 `
I am doing any wrong?

**Comment by PARODBE** [comment]
Hi,

I obtain the same error, any solutions for this?

**Comment by eloyfelix** [comment]
Hi,

Are you still having issues with it? Could you please share a minimal reproducible example without using other third libraries (pandas...)?

The web services (this library is working on top of it) seems to be working fine.

@juanfmx2

**Comment by PARODBE** [comment]
Now, it is working fine.

Thanks!

**Comment by YojanaGadiya** [comment]
@eloyfelix I get the same error. It looks like the error probably arises due to the results containing truncated data cell no.9 in the [example notebook](https://github.com/chembl/chembl_webresource_client/blob/master/demo_wrc.ipynb). This causes the breaking of the loop at some point. Please can you suggest a way to extract all the results without any truncation?

Thank You.

**Comment by khanmf** [comment]
@eloyfelix @PARODBE @FelPVic @YojanaGadiya I am getting the same error. Please help me in resolving the issue if anyone of you guyz know the solution.

Thanks in advance

**Comment by ailnicka** [comment]
I'm also getting this error (500) now, whenever I have a longer list of targets for which I try to get activities. Is there a problem with EBI server?
