### ISSUE TITLE
chembl_webresource_client.__version__()

### ISSUE THREAD

**Issue by soerendip42** [chembl/chembl_webresource_client#12]
It would be nice to have the a convenient function:

`chembl_webresource_client.__version__()`
or
`chembl_webresource_client.version()`

to query the current version  of the client.

**Comment by mnowotka** [comment]
Hi Soeren,

We have it already but it's constant instead of the function, please use:

    from chembl_webresource_client import __version__

**Comment by soerendip42** [comment]
Ah, ok!! I was trying
__version__()
Sorry and thanks!

**Comment by mnowotka** [comment]
No worries :)
