### ISSUE TITLE
HttpApplicationError

### ISSUE THREAD

**Issue by meghanakaranam1** [chembl/chembl_webresource_client#129]
hi,
I'm getting this error. Is there a problem with my code, or is the api having any server side issues?
please help me out on this @eloyfelix @nclopezo @mnowotka @fredrikw @sshojiro 

![image](https://github.com/chembl/chembl_webresource_client/assets/81307675/1254a1e3-4675-4f1c-a130-f79167d0d3df)

**Comment by Acario** [comment]
I am getting the same error. My code was working fine two weekends ago. Today I tried it on the same compound as two weeks ago and this error came up. I would like to know what is going on as well here.

**Comment by fredrikw** [comment]
Hello,
Did you check if the api hade any problems? Do you have a minimum reproducable example? It would be a lot better if you copied and pasted the code and error message as text instead of a screen shot. For one, it's possible to copy and paste to test instead of typing everything manually. Also, you have cut the error message, did it include anymore specifics on the server error?
I don't have the library installed on my main computer at the moment so I can't easily try but the API seems to work. (Checkable at https://www.ebi.ac.uk/chembl/api/data/docs)

**Comment by Acario** [comment]
Here is the code I am running:

`from chembl_webresource_client.new_client import new_client`

Here is the error:

`Exception                                 Traceback (most recent call last)
Input In [1], in <cell line: 1>()
---> 1 from chembl_webresource_client.new_client import new_client

File ~\anaconda3\lib\site-packages\chembl_webresource_client\new_client.py:65, in <module>
     60     return client
     63 #-----------------------------------------------------------------------------------------------------------------------
---> 65 new_client = client_from_url(Settings.Instance().NEW_CLIENT_URL + '/spore')

File ~\anaconda3\lib\site-packages\chembl_webresource_client\new_client.py:27, in client_from_url(url, base_url)
     25 res = requests.get(url)
     26 if not res.ok:
---> 27     raise Exception('Error getting schema from url {0} with status {1} and msg {2}'.format(url, res.status_code, res.text))
     28 schema = res.json()
     29 if 'base_url' not in schema:

Exception: Error getting schema from url https://www.ebi.ac.uk/chembl/api/data/spore with status 500 and msg <!doctype html>
<html lang="en" class="vf-no-js">
  <head>
    <script>
// Detect if JS is on and swap vf-no-js for vf-js on the html element
(function(H){H.className=H.className.replace(/\bvf-no-js\b/,'vf-js')})(document.documentElement);
</script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Error: 500 | EMBLâs European Bionformatics Institute</title>



    <link rel="icon" type="image/x-icon"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/favicon.ico" />
<link rel="icon" type="image/png"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/favicon-32x32.png" />
<link rel="icon" type="image/png" sizes="192Ã192"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/android-chrome-192x192.png" />

<link rel="apple-touch-icon-precomposed" sizes="114x114"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/apple-icon-114x114.png" />

<link rel="apple-touch-icon-precomposed" sizes="72x72"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/apple-icon-72x72.png" />

<link rel="apple-touch-icon-precomposed" sizes="144x144"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/apple-icon-144x144.png" />

<link rel="apple-touch-icon-precomposed"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/apple-icon-57x57.png" />

<link rel="mask-icon"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/safari-pinned-tab.svg"
  color="#ffffff" /> 
<meta name="msapplication-TileColor" content="#2b5797" /> 
<meta name="msapplication-TileImage"
  content="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/mstile-144x144.png" />






    
    <meta class="swiftype" name="what" data-type="string" content="none" />
    <meta class="swiftype" name="where" data-type="string" content="EMBL-EBI" />


    
    <meta name="title" content="Error: 500">
    <meta name="author" content="European Bioinformatics Institute">
    <meta name="robots" content="index, follow">
    <meta name="keywords" content="">
    <meta name="description" content="">

    
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://www.ebi.ac.uk/info/error-pages/500-standalone/">
    <meta property="og:title" content="Error: 500">
    <meta property="og:description" content="">


    
    <meta property="twitter:card" content="summary_large_image">
    <meta property="og:url" content="https://www.ebi.ac.uk/info/error-pages/500-standalone/">
    <meta property="twitter:title" content="Error: 500">
    <meta property="twitter:description" content="">


    
    <meta name="embl:who" content="EMBL-EBI Web Dev">
    <meta name="embl:where" content="EMBL-EBI">
    <meta name="embl:what" content="none">
    <meta name="embl:active" content="where">

    
    <meta name="embl:utility" content="10">
    <meta name="embl:reach" content="0">

    
    <meta name="embl:maintainer" content="EMBL-EBI Web Dev">
    <meta name="embl:last-review" content="2021.04.01">
    <meta name="embl:review-cycle" content="365">
    <meta name="embl:expiry" content="never">

    
    <meta name="vf:page-type" content="404;dimension1">

    
<link rel="stylesheet" href="https://assets.emblstatic.net/vf/v2.5.7/css/styles.css">

<script src="https://assets.emblstatic.net/vf/v2.5.7/scripts/scripts.js"></script>
<head>
  <body class="vf-body vf-stack vf-stack--400">
    <style>head, title, link, meta, style, script {--vf-stack-margin--custom: 0; }</style>

    

    <link rel="stylesheet" href="https://assets.emblstatic.net/vf/v2.4.5/assets/ebi-header-footer/ebi-header-footer.css" type="text/css" media="all">
    <header id="masthead-black-bar" class="clearfix masthead-black-bar | ebi-header-footer vf-content vf-u-fullbleed"></header>




<style>
  .embl-grid {
    margin-bottom: 48px;
  }
</style>

<section class="vf-intro" id="500">

  <div></div>

  <div class="vf-stack">

  <h1 class="vf-intro__heading ">Error: 500</h1>
<p class="vf-lede">There was a technical error.</p>


<p class="vf-intro__text">Something has gone wrong with our web server when attempting to make this page.</p><p class="vf-intro__text">Unfortunately, the service you are trying to access is currently unavailable. <br>Please try again later.</p>
  </div>
</section>


<section class="embl-grid embl-grid--has-centered-content">
  <div></div>
 <section>
      <form id="ebi_search" action="/ebisearch/search.ebi" class="vf-form vf-form--search vf-form--search--mini | vf-sidebar vf-sidebar--end">
        <div class="vf-sidebar__inner" style="flex-wrap: nowrap;">
          <div class="vf-form__item">
            <label class="vf-form__label vf-u-sr-only | vf-search__label" for="searchitem">Search</label>
            <input name="query" type="search" placeholder="Find a gene, protein or chemical" id="searchitem" class="vf-form__input" required="" spellcheck="false" data-ms-editor="true">
            <input name="requestFrom" id="requestFrom" type="hidden" class="vf-form__input" value="ebi_index">
          </div>
          <div class="vf-form__item">
            <select name="db" id="db" tabindex="1" class="vf-form__select" style="max-width: 150px">
              <option value="allebi">All</option>
              <optgroup label="Science search">
                <option value="genomes">Genomes &amp; metagenomes</option>
                <option value="nucleotideSequences">Nucleotide sequences</option>
                <option value="proteinSequences">Protein sequences</option>
                <option value="smallMolecules">Small molecules</option>
                <option value="geneExpression">Gene expression</option>
                <option value="geneDiseaseAssociations">Gene-Disease Associations</option>
                <option value="diseases">Diseases</option>
                <option value="molecularInteractions">Molecular interactions</option>
                <option value="reactionsPathways">Reactions &amp; pathways</option>
                <option value="proteinFamilies">Protein families</option>
                <option value="literature">Literature</option>
                <option value="ontologies">Samples &amp; ontologies</option>
              </optgroup>
              <optgroup label="Search web content">
                <option value="ebiweb_people">EMBL-EBI People</option>
                <option value="ebiweb">EMBL-EBI web</option>
                
              </optgroup>
            </select>
          </div>


          <button type="submit" class="vf-search__button | vf-button vf-button--primary">
            <span class="vf-button__text">Search</span>
          </button>
        </div>
      </form>
      <p class="vf-text-body--5 vf-u-margin__bottom--0">
        Example searches: <a class="vf-link" href="/ebisearch/search.ebi?db=allebi&amp;requestFrom=ebi_index&amp;query=blast">blast</a>
        <a class="vf-link" href="/ebisearch/search.ebi?db=allebi&amp;query=keratin&amp;requestFrom=ebi_index">keratin</a>
        <a class="vf-link" href="/ebisearch/search.ebi?db=allebi&amp;query=bfl1&amp;requestFrom=ebi_index">bfl1</a>
        | <a class="vf-link" href="https://www.ebi.ac.uk/ebisearch/overview.ebi/about">About EBI Search</a>
      </p>
    </section>
</section>

<section class="embl-grid">
  <div></div>
  <div class="vf-content">
    <h3>Need assistance?</h3>
    <a class="vf-button vf-button--primary" href="https://www.ebi.ac.uk/support/error">Contact our support team</a>
  </div>
</section>

    



<link rel="import" href="https://www.embl.org/api/v1/pattern.html?filter-content-type=article&filter-id=106902&pattern=node-body&source=contenthub" data-target="self" data-embl-js-content-hub-loader>

    <script src="https://assets.emblstatic.net/vf/v2.4.9/scripts/scripts.js"></script>

<div class="vf-u-display-none" data-protection-message-disable="true"></div>


<script nomodule crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?flags=gated&features=default"></script>

<script defer="defer" src="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/js/script.js"></script>
<link rel="stylesheet" href="//ebi.emblstatic.net/web_guidelines/EBI-Icon-fonts/v1.3/fonts.css" type="text/css" media="all" />


<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-629242-1', 'auto');
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>


<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", function(event) {

        //- Code to execute when only the HTML document is loaded.
        //- This doesn't wait for stylesheets,
        // images, and subframes to finish loading.
  });
</script>

  </body>
</html>`

**Comment by Acario** [comment]
Sometimes it does successfully load the package but then I try to run the package over some compounds and get this below.

Code:
`chembl_ids=[] 
for h in range(0,len(comps)):
    molecule=new_client.molecule
    molS=molecule.filter(molecule_synonyms__molecule_synonym__iexact=comps[h])
    if len(molS)>0:
        chembl_ids.append(molS[0]['molecule_chembl_id']) # Synonym hit
    else:
        chembl_ids.append(0)`
        
This is the error here:

`HttpApplicationError                      Traceback (most recent call last)
Input In [11], in <cell line: 2>()
      3 molecule=new_client.molecule
      4 molS=molecule.filter(molecule_synonyms__molecule_synonym__iexact=comps[h])
----> 5 if len(molS)>0:
      6     chemblSyn.append(molS[0]['molecule_chembl_id']) # Synonym hit
      7 else:

File ~\anaconda3\lib\site-packages\chembl_webresource_client\query_set.py:97, in QuerySet.__len__(self)
     95 if not self.can_filter:
     96     return 1
---> 97 return len(self.query)

File ~\anaconda3\lib\site-packages\chembl_webresource_client\url_query.py:144, in UrlQuery.__len__(self)
    142     return
    143 if not self.api_total_count:
--> 144     self.get_page()
    145 return self.api_total_count

File ~\anaconda3\lib\site-packages\chembl_webresource_client\url_query.py:394, in UrlQuery.get_page(self)
    392 self.logger.info('From cache: {0}'.format(res.from_cache if hasattr(res, 'from_cache') else False))
    393 if not res.ok:
--> 394     handle_http_error(res)
    395 if self.frmt == 'json':
    396     json_data = res.json()

File ~\anaconda3\lib\site-packages\chembl_webresource_client\http_errors.py:113, in handle_http_error(request)
    111 exception_class = status_to_exception.get(request.status_code, BaseHttpException)
    112 if request.text:
--> 113     raise exception_class(request.url, request.text)
    114 raise exception_class(request.url, request.content)

HttpApplicationError: Error for url https://www.ebi.ac.uk/chembl/api/data/molecule.json, server response: <!doctype html>
<html lang="en" class="vf-no-js">
  <head>
    <script>
// Detect if JS is on and swap vf-no-js for vf-js on the html element
(function(H){H.className=H.className.replace(/\bvf-no-js\b/,'vf-js')})(document.documentElement);
</script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <title>Error: 500 | EMBLâs European Bionformatics Institute</title>



    <link rel="icon" type="image/x-icon"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/favicon.ico" />
<link rel="icon" type="image/png"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/favicon-32x32.png" />
<link rel="icon" type="image/png" sizes="192Ã192"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/android-chrome-192x192.png" />

<link rel="apple-touch-icon-precomposed" sizes="114x114"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/apple-icon-114x114.png" />

<link rel="apple-touch-icon-precomposed" sizes="72x72"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/apple-icon-72x72.png" />

<link rel="apple-touch-icon-precomposed" sizes="144x144"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/apple-icon-144x144.png" />

<link rel="apple-touch-icon-precomposed"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/apple-icon-57x57.png" />

<link rel="mask-icon"
  href="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/safari-pinned-tab.svg"
  color="#ffffff" /> 
<meta name="msapplication-TileColor" content="#2b5797" /> 
<meta name="msapplication-TileImage"
  content="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/images/logos/EMBL-EBI/favicons/mstile-144x144.png" />






    
    <meta class="swiftype" name="what" data-type="string" content="none" />
    <meta class="swiftype" name="where" data-type="string" content="EMBL-EBI" />


    
    <meta name="title" content="Error: 500">
    <meta name="author" content="European Bioinformatics Institute">
    <meta name="robots" content="index, follow">
    <meta name="keywords" content="">
    <meta name="description" content="">

    
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://www.ebi.ac.uk/info/error-pages/500-standalone/">
    <meta property="og:title" content="Error: 500">
    <meta property="og:description" content="">


    
    <meta property="twitter:card" content="summary_large_image">
    <meta property="og:url" content="https://www.ebi.ac.uk/info/error-pages/500-standalone/">
    <meta property="twitter:title" content="Error: 500">
    <meta property="twitter:description" content="">


    
    <meta name="embl:who" content="EMBL-EBI Web Dev">
    <meta name="embl:where" content="EMBL-EBI">
    <meta name="embl:what" content="none">
    <meta name="embl:active" content="where">

    
    <meta name="embl:utility" content="10">
    <meta name="embl:reach" content="0">

    
    <meta name="embl:maintainer" content="EMBL-EBI Web Dev">
    <meta name="embl:last-review" content="2021.04.01">
    <meta name="embl:review-cycle" content="365">
    <meta name="embl:expiry" content="never">

    
    <meta name="vf:page-type" content="404;dimension1">

    
<link rel="stylesheet" href="https://assets.emblstatic.net/vf/v2.5.7/css/styles.css">

<script src="https://assets.emblstatic.net/vf/v2.5.7/scripts/scripts.js"></script>
<head>
  <body class="vf-body vf-stack vf-stack--400">
    <style>head, title, link, meta, style, script {--vf-stack-margin--custom: 0; }</style>

    

    <link rel="stylesheet" href="https://assets.emblstatic.net/vf/v2.4.5/assets/ebi-header-footer/ebi-header-footer.css" type="text/css" media="all">
    <header id="masthead-black-bar" class="clearfix masthead-black-bar | ebi-header-footer vf-content vf-u-fullbleed"></header>




<style>
  .embl-grid {
    margin-bottom: 48px;
  }
</style>

<section class="vf-intro" id="500">

  <div></div>

  <div class="vf-stack">

  <h1 class="vf-intro__heading ">Error: 500</h1>
<p class="vf-lede">There was a technical error.</p>


<p class="vf-intro__text">Something has gone wrong with our web server when attempting to make this page.</p><p class="vf-intro__text">Unfortunately, the service you are trying to access is currently unavailable. <br>Please try again later.</p>
  </div>
</section>


<section class="embl-grid embl-grid--has-centered-content">
  <div></div>
 <section>
      <form id="ebi_search" action="/ebisearch/search.ebi" class="vf-form vf-form--search vf-form--search--mini | vf-sidebar vf-sidebar--end">
        <div class="vf-sidebar__inner" style="flex-wrap: nowrap;">
          <div class="vf-form__item">
            <label class="vf-form__label vf-u-sr-only | vf-search__label" for="searchitem">Search</label>
            <input name="query" type="search" placeholder="Find a gene, protein or chemical" id="searchitem" class="vf-form__input" required="" spellcheck="false" data-ms-editor="true">
            <input name="requestFrom" id="requestFrom" type="hidden" class="vf-form__input" value="ebi_index">
          </div>
          <div class="vf-form__item">
            <select name="db" id="db" tabindex="1" class="vf-form__select" style="max-width: 150px">
              <option value="allebi">All</option>
              <optgroup label="Science search">
                <option value="genomes">Genomes &amp; metagenomes</option>
                <option value="nucleotideSequences">Nucleotide sequences</option>
                <option value="proteinSequences">Protein sequences</option>
                <option value="smallMolecules">Small molecules</option>
                <option value="geneExpression">Gene expression</option>
                <option value="geneDiseaseAssociations">Gene-Disease Associations</option>
                <option value="diseases">Diseases</option>
                <option value="molecularInteractions">Molecular interactions</option>
                <option value="reactionsPathways">Reactions &amp; pathways</option>
                <option value="proteinFamilies">Protein families</option>
                <option value="literature">Literature</option>
                <option value="ontologies">Samples &amp; ontologies</option>
              </optgroup>
              <optgroup label="Search web content">
                <option value="ebiweb_people">EMBL-EBI People</option>
                <option value="ebiweb">EMBL-EBI web</option>
                
              </optgroup>
            </select>
          </div>


          <button type="submit" class="vf-search__button | vf-button vf-button--primary">
            <span class="vf-button__text">Search</span>
          </button>
        </div>
      </form>
      <p class="vf-text-body--5 vf-u-margin__bottom--0">
        Example searches: <a class="vf-link" href="/ebisearch/search.ebi?db=allebi&amp;requestFrom=ebi_index&amp;query=blast">blast</a>
        <a class="vf-link" href="/ebisearch/search.ebi?db=allebi&amp;query=keratin&amp;requestFrom=ebi_index">keratin</a>
        <a class="vf-link" href="/ebisearch/search.ebi?db=allebi&amp;query=bfl1&amp;requestFrom=ebi_index">bfl1</a>
        | <a class="vf-link" href="https://www.ebi.ac.uk/ebisearch/overview.ebi/about">About EBI Search</a>
      </p>
    </section>
</section>

<section class="embl-grid">
  <div></div>
  <div class="vf-content">
    <h3>Need assistance?</h3>
    <a class="vf-button vf-button--primary" href="https://www.ebi.ac.uk/support/error">Contact our support team</a>
  </div>
</section>

    



<link rel="import" href="https://www.embl.org/api/v1/pattern.html?filter-content-type=article&filter-id=106902&pattern=node-body&source=contenthub" data-target="self" data-embl-js-content-hub-loader>

    <script src="https://assets.emblstatic.net/vf/v2.4.9/scripts/scripts.js"></script>

<div class="vf-u-display-none" data-protection-message-disable="true"></div>


<script nomodule crossorigin="anonymous" src="https://polyfill.io/v3/polyfill.min.js?flags=gated&features=default"></script>

<script defer="defer" src="https://ebi.emblstatic.net/web_guidelines/EBI-Framework/v1.4/js/script.js"></script>
<link rel="stylesheet" href="//ebi.emblstatic.net/web_guidelines/EBI-Icon-fonts/v1.3/fonts.css" type="text/css" media="all" />


<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-629242-1', 'auto');
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>


<script type="text/javascript">
  document.addEventListener("DOMContentLoaded", function(event) {

        //- Code to execute when only the HTML document is loaded.
        //- This doesn't wait for stylesheets,
        // images, and subframes to finish loading.
  });
</script>

  </body>
</html>
`

**Comment by eloyfelix** [comment]
@juanfmx2 @nclopezo could you please take a look at it?

cc: @BZdrazil @FionaEBI

**Comment by fredrikw** [comment]
It's working perfectly fine for me both through the package and directly on the API docs page. Most likely they had some problems on the API side. The error messages certainly indicates that. You get a 500-error from the API. So I wouldn't say it's a bug with the client package.

**Comment by juanfmx2** [comment]
@fredrikw @Acario @meghanakaranam1 sorry for the late response, we were having intermittent issues with our infrastructure, but the service should  be stable now. Please let me know if you are experiencing any other issues.

**Comment by spchhetri** [comment]
![Screenshot 2024-11-18 161233](https://github.com/user-attachments/assets/0daf4f72-46c1-495c-8d0e-a3761eb5c84c)
I am experiencing this issue again.

**Comment by spchhetri** [comment]
@juanfmx2

**Comment by juanfmx2** [comment]
Hi @sandy1723 the endpoints and in general the web services seem to be working normally at the moment.
https://wwwdev.ebi.ac.uk/chembl/api/data/activity.json
https://wwwdev.ebi.ac.uk/chembl/api/data/status.json

Could you please share a bit more details about the filtering you are performing when you instantiate the bioactivities object.

**Comment by spchhetri** [comment]
![Screenshot 2024-11-18 192018](https://github.com/user-attachments/assets/7df6dd89-d653-4379-9ee5-77a8ccfa64d7)
![Screenshot 2024-11-18 192048](https://github.com/user-attachments/assets/db1ac6df-4e22-4936-a17b-c7dc549c58d8)
 @juanfmx2 These are the codes prior to the one I mentioned above.

**Comment by juanfmx2** [comment]
I will need to give this a review, as checking the URL's in the browser for the equivalent queries they all load correctly.

**Comment by spchhetri** [comment]
@juanfmx2 What does this mean? Is my code incorrect or is there a problem with my browser? I am using google colab to write codes.

**Comment by juanfmx2** [comment]
your code looks correct, so I need to investigate why it is not working

**Comment by juanfmx2** [comment]
Hi @sandy1723 please have a look at this IPython Notebook
https://colab.research.google.com/drive/1VNUsSC-VS8VcmYGsbqxlsTBlyR8oIzox?usp=sharing

Particularly lines 6 to 9 and 16. This will increase your success at iterating all the results. However, queries on the activity endpoint are very heavy due to the large amount of records on the activity table (over 10 million). I would recommend using more specific queries that yield less than 1000 total results at a time.

The main issue you are experiencing at the moment is request timeouts. We are thinking about how to improve stability for this more complex queries performance.

**Comment by spchhetri** [comment]
@juanfmx2 Thanks a lot for your help. I appreciate it. The codes I sent you yesterday seem to work fine for now. If I encounter the error again, I will use the codes you provided.
