### ISSUE TITLE
No module names packages.urllib3.util

### ISSUE THREAD

**Issue by corinabioinformatic** [chembl/chembl_webresource_client#13]
I installed by the way of this website [http://chembl.blogspot.co.uk/2014/05/a-python-client-for-accessing-chembl.html](url) the module to access to ChemBL data. But when I try to run the example from the web [http://chembl.blogspot.co.uk/2014/05/a-python-client-for-accessing-chembl.html](url) to retrieve drug indication, I got the same error.

I've got the urllib3 library installed and if I import 'chembl_webresource_client'  module it works fine. But with the new client it doesn't work. 

The error says:
`Traceback (most recent call last):
  File "test_ChemBLindication.py", line 1, in <module>
    from chembl_webresource_client.new_client import new_client
  File "/usr/local/lib/python2.7/dist-packages/chembl_webresource_client/new_client.py", line 10, in <module>
    from chembl_webresource_client.query_set import QuerySet
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/chembl_webresource_client/query_set.py", line 8, in <module>
    from chembl_webresource_client.url_query import UrlQuery
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/chembl_webresource_client/url_query.py", line 21, in <module>
    from requests.packages.urllib3.util import Retry
  File "/usr/local/lib/python2.7/dist-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
ImportError: No module named packages.urllib3.util
`

**Comment by corinabioinformatic** [comment]
Also I have to mention that when I run tests.py it retrieves me error too.

**Comment by mnowotka** [comment]
Hi,
Thanks for reporting this. Can you tell me:

1. Python version you are using
2. The output of the `pip freeze` command?

**Comment by corinabioinformatic** [comment]
Python 2.7.6 (default, Jun 22 2015, 17:58:13)

BeautifulSoup==3.2.1
Jinja2==2.7.2
MarkupSafe==0.18
MySQL-python==1.2.3
PAM==0.4.2
Pillow==2.3.0
Pygments==2.1.3
Twisted-Core==13.2.0
Twisted-Web==13.2.0
VTK==5.8.0
XlsxWriter==0.8.4
apptools==4.4.0
apt-xapian-index==0.45
argparse==1.2.1
beautifulsoup4==4.2.1
biopython==1.66
chardet==2.0.1
chembl-webresource-client==0.8.36
colorama==0.2.5
command-not-found==0.3
configobj==4.7.2
cvxopt==1.1.4
debtagshw==0.1
decorator==3.4.0
defer==1.0.6
dirspec==13.10
easydict==1.6
envisage==4.5.1
fisher==0.1.4
gevent==1.1.1
goatools==0.6.4
greenlet==0.4.9
grequests==0.2.0
html2text==2016.1.8
html5lib==0.999
httplib2==0.8
ipython==1.2.1
joblib==0.7.1
lxml==3.3.3
matplotlib==1.3.1
mayavi==4.4.4
networkx==1.8.1
nose==1.3.1
numexpr==2.2.2
numpy==1.8.2
oauthlib==0.6.1
oneconf==0.3.7.14.04.1
openpyxl==1.7.0
pandas==0.13.1
patsy==0.2.1
pexpect==3.1
piston-mini-client==0.7.5
psutil==1.2.1
pyOpenSSL==0.13
pycrypto==2.6.1
pycups==1.9.66
pycurl==7.19.3
pyface==5.0.0
pygobject==3.12.0
pyparsing==2.0.1
pyserial==2.6
pysmbc==1.0.14.1
python-apt==0.9.3.5ubuntu2
python-dateutil==1.5
python-debian==0.1.21-nmu2ubuntu2
pytz==2012c
pyxdg==0.25
pyzmq==14.0.1
reportlab==3.0
requests==2.2.1
requests-cache==0.4.12
scipy==0.13.3
sessioninstaller==0.0.0
simplegeneric==0.8.1
simplejson==3.3.1
six==1.5.2
software-center-aptd-plugins==0.0.0
statsmodels==0.5.0
sympy==0.7.4.1
tables==3.1.1
tornado==3.1.1
traits==4.5.0
traitsui==5.0.0
urllib3==1.7.1
wget==3.2
wheel==0.24.0
wsgiref==0.1.2
wxPython==2.8.12.1
wxPython-common==2.8.12.1
xlrd==0.9.2
xlwt==0.7.5
zope.interface==4.0.5

**Comment by mnowotka** [comment]
OK, can you upgrade `urllib3` and `requests`?

    pip install -U urllib3
    pip install -U requests

**Comment by corinabioinformatic** [comment]
I did it but I've the same problem. After the upgrade in both cases there
is a sucessful instalation. I will send you the details in the next message
from croca@ebi.ac.uk

**Comment by corinabioinformatic** [comment]
chembl/chembl_webresource_client
reply@reply.github.com

**Comment by corinabioinformatic** [comment]
**pip install -U urllib3**

Downloading/unpacking urllib3 from https://pypi.python.org/packages/py2.py3/u/urllib3/urllib3-1.15.1-py2.py3-none-any.whl#md5=00a5541c03971b9a3a2b6517e8da4869
  Downloading urllib3-1.15.1-py2.py3-none-any.whl (92kB): 92kB downloaded
Installing collected packages: urllib3
  Found existing installation: urllib3 1.7.1
    Not uninstalling urllib3 at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed urllib3
Cleaning up...
** pip install -U requests**
Downloading/unpacking requests from https://pypi.python.org/packages/2.7/r/requests/requests-2.9.1-py2.py3-none-any.whl#md5=58a444aaa02780ad01983f5f540e67b2
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB): 501kB downloaded
Installing collected packages: requests
  Found existing installation: requests 2.2.1
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed requests
Cleaning up...

**Comment by mnowotka** [comment]
Please notice these lines:

    Not uninstalling urllib3 at /usr/lib/python2.7/dist-packages, owned by OS
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS

This means that no upgrade was performed in fact.
And the reason seems to be the fact that you are not using Python in an isolated environment, such us [virtualenv](https://virtualenv.pypa.io/en/latest/) or [conda](http://conda.pydata.org/docs/intro.html).

**Comment by corinabioinformatic** [comment]
Ok. Finnally I installed the virtualenv following the web isntructions. And I was able to run the following example from the website but It returns this error:

**test_ChemBLindication.py**
`from chembl_webresource_client.new_client import new_client

go_slim = new_client.go_slim

# retrieving go slims by GO IDs:
go_slim.get(['GO:0000229','GO:0005730'])

# filtering go slims:
go_slim.filter(aspect="F").filter(class_level__gte=3).exists()

#ordering go slims:
go_slim.order_by('aspect')

drug_indication = new_client.drug_indication

# retrieving drug indicatios by ids:
drug_indication.get([22614, 22615])

# filtering drug indications:
drug_indication.filter(max_phase_for_ind__lte=3, efo_term__startswith='OSTEOARTHRITIS')

# ordering drug indications:
drug_indication.order_by('mesh_id')

metabolism = new_client.metabolism

# retrieving metablisms by ids:
metabolism.get([149,151])

# filtering metabolisms
metabolism.filter(met_conversion__startswith='hydroxylation', met_comment__icontains='liver', enzyme_name__isnull=False)

# ordering metabolisms:
metabolism.order_by('-pathway_id')

`

The error says: 
`/ENV/bin/python MyScriptsInENV/test_ChemBLindication.py
Traceback (most recent call last):
  File "MyScriptsInENV/test_ChemBLindication.py", line 9, in <module>
    go_slim.filter(aspect="F").filter(class_level__gte=3).exists()
  File "/home/koryclik/Documents/ScriptsPy/ChemBL/ENV/local/lib/python2.7/site-packages/chembl_webresource_client/query_set.py", line 187, in exists
    return type(self).__bool__(self)
  File "/home/koryclik/Documents/ScriptsPy/ChemBL/ENV/local/lib/python2.7/site-packages/chembl_webresource_client/query_set.py", line 133, in __bool__
    return bool(len(self))
  File "/home/koryclik/Documents/ScriptsPy/ChemBL/ENV/local/lib/python2.7/site-packages/chembl_webresource_client/query_set.py", line 98, in __len__
    return len(self.query)
  File "/home/koryclik/Documents/ScriptsPy/ChemBL/ENV/local/lib/python2.7/site-packages/chembl_webresource_client/url_query.py", line 151, in __len__
    self.get_page()
  File "/home/koryclik/Documents/ScriptsPy/ChemBL/ENV/local/lib/python2.7/site-packages/chembl_webresource_client/url_query.py", line 395, in get_page
    handle_http_error(res)
  File "/home/koryclik/Documents/ScriptsPy/ChemBL/ENV/local/lib/python2.7/site-packages/chembl_webresource_client/http_errors.py", line 113, in handle_http_error
    raise exception_class(request.url, request.text)
chembl_webresource_client.http_errors.HttpServiceUnavailable: Error for url https://www.ebi.ac.uk/chembl/api/data/go_slim.json, server response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Temporarily Unavailable</title>
</head><body>
<h1>Service Temporarily Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
<hr>
<address>Apache/2.2.15 (Red Hat) Server at www.ebi.ac.uk Port 80</address>
</body></html>`

**Comment by mnowotka** [comment]
Interesting, the URL specified in the error message seems to be working fine: https://www.ebi.ac.uk/chembl/api/data/go_slim.json. Can you please try once again?

**Comment by corinabioinformatic** [comment]
Traceback (most recent call last):
  File "MyScriptsInENV/test_ChemBLindication.py", line 9, in <module>
    go_slim.filter(aspect="F").filter(class_level__gte=3).exists()
  File "/home/koryclik/Documents/ScriptsPy/ChemBL/ENV/local/lib/python2.7/site-packages/chembl_webresource_client/query_set.py", line 187, in exists
    return type(self).__bool__(self)
  File "/home/koryclik/Documents/ScriptsPy/ChemBL/ENV/local/lib/python2.7/site-packages/chembl_webresource_client/query_set.py", line 133, in __bool__
    return bool(len(self))
  File "/home/koryclik/Documents/ScriptsPy/ChemBL/ENV/local/lib/python2.7/site-packages/chembl_webresource_client/query_set.py", line 98, in __len__
    return len(self.query)
  File "/home/koryclik/Documents/ScriptsPy/ChemBL/ENV/local/lib/python2.7/site-packages/chembl_webresource_client/url_query.py", line 151, in __len__
    self.get_page()
  File "/home/koryclik/Documents/ScriptsPy/ChemBL/ENV/local/lib/python2.7/site-packages/chembl_webresource_client/url_query.py", line 395, in get_page
    handle_http_error(res)
  File "/home/koryclik/Documents/ScriptsPy/ChemBL/ENV/local/lib/python2.7/site-packages/chembl_webresource_client/http_errors.py", line 113, in handle_http_error
    raise exception_class(request.url, request.text)
chembl_webresource_client.http_errors.HttpServiceUnavailable: Error for url https://www.ebi.ac.uk/chembl/api/data/go_slim.json, server response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Temporarily Unavailable</title>
</head><body>
<h1>Service Temporarily Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
<hr>
<address>Apache/2.2.15 (Red Hat) Server at www.ebi.ac.uk Port 80</address>
</body></html>

The same error. Are you doing any maintance of the server now? 
I had the same problem from the NIH and it was becuase that. 
``

**Comment by mnowotka** [comment]
We are not doing any maintenance now.

From my python console:

    from chembl_webresource_client.new_client import new_client
    go_slim = new_client.go_slim
    go_slim.filter(aspect="F").filter(class_level__gte=3).exists()
    True

The URL: https://www.ebi.ac.uk/chembl/api/data/go_slim.json?ascpect=F&class_level__gte=3 works fine as well.

**Comment by corinabioinformatic** [comment]
Than you for all.
Finally I managed run part of the code. I was trying to found where is the drug_indication number from? 

But it didn't match with the EFO or MEsh code. I searched also the code in the drug_indication references without any success. Could you tell me where could I found the code for 'Vasculitis' for example? 
**My code**: 

from chembl_webresource_client.new_client import new_client

drug_indication = new_client.drug_indication
print("==============")

# retrieving drug indicatios by ids:
drug_indication2  = drug_indication.get([21657])


drug_indication.order_by('mesh_id')
print(drug_indication2)

**Comment by agaulton** [comment]
The drugind_id returned by the web service call is just a primary key corresponding to a combination of the compound (molecule_chembl_id), efo_id and mesh_id.

If you wanted to do a text search for all drug indications corresponding to 'Vasculitis', you could do so like this (or the same with mesh_heading): 
https://www.ebi.ac.uk/chembl/api/data/drug_indication.json?efo_term__iexact=Vasculitis

Or with the client:
```
from chembl_webresource_client.new_client import new_client
drug_indication = new_client.drug_indication
res = drug_indication.filter(efo_term__iexact=“Vasculitis”)
```

However, if you want to be sure of identifying the all relevant EFO or MeSH IDs for a given disease/indication you may also want to use external services e.g., for EFO there is a lookup service:
http://www.ebi.ac.uk/ols/beta/search?q=vasculitis&groupField=iri&exact=on&start=0&ontology=efo
Then you can query with the EFO ID like this:
https://www.ebi.ac.uk/chembl/api/data/drug_indication.json?efo_id=EFO:0006803

Not sure if this answers your question, so let me know if I've misunderstood what you're asking...

**Comment by karinlah** [comment]
I had the same issue as well, on Ubuntu machine and the problem was that the Ubuntu OS is using urilib3 as well, so it didn't recognize the package installed through pip.
the solution was to remove the ubunto urllib3 package and install it again with pip:
apt-get remove python-urllib3 
sudo pip install urllib3
