### ISSUE TITLE
Error while trying to connect (sqlite3.DatabaseError: database disk image is malformed)

### ISSUE THREAD

**Issue by Andzerakk** [chembl/chembl_webresource_client#137]
Hello, even when I'm trying the most basic things like 
```
import pandas as pd 
from chembl_webresource_client.new_client import new_client 


activities = new_client.activity.filter(target_chembl_id__in=['CHEMBL5552','CHEMBL1075195']  
                                        , pchembl_value__gte=5                               
                                        , assay_type='B'                                   
                                       ).only(['target_chembl_id', 'target_pref_name', 'parent_molecule_chembl_id' 
                                                               ,'molecule_chembl_id','molecule_pref_name', 'pchembl_value'])

act_df = pd.DataFrame(activities)
act_df)`
```
I get 'sqlite3.DatabaseError: database disk image is malformed' error. Is this problem on my end and my code is at fault?

**Comment by eloyfelix** [comment]
It seems like the SQLite cache database the library uses might be corrupted. Could you please try to delete it?

In Linux/MacOS the file should be in your home folder and should have a name like this: .chembl_ws_client__0.10.9

To delete it `rm ~/.chembl_ws_client__0.10.9`

**Comment by Andzerakk** [comment]
> It seems like the SQLite cache database the library uses might be corrupted. Could you please try to delete it?
> 
> In Linux/MacOS the file should be in your home folder and should have a name like this: .chembl_ws_client__0.10.9
> 
> To delete it `rm ~/.chembl_ws_client__0.10.9`

Much obliged! It helped with the issue!
