### ISSUE TITLE
Getting data from chembl 21 rather than 22?

### ISSUE THREAD

**Issue by izharw** [chembl/chembl_webresource_client#15]
Hi,
I'm running the simple script below to retrieve all targets from CHEMBL but the number of targets I'm getting matches the total number of targets in ChEMBL 21 and not 22. Am I missing something?
I'm using the latest version and removed all cache files.

Thanks,
Izzy
-----
from chembl_webresource_client import *
targets = TargetResource()
all_targets = targets.get_all()
print "Retrieved", len( all_targets ), "targets"

> python ./TEST.py 
Retrieved 11019 targets

**Comment by mnowotka** [comment]
The client caches data. If you are using an older client the cache will be stored in the current directory, in the file with *.sqlite extension. Newer client versions store cache in home directory in the hidden file (hidden means that the name of file starts with a dot). For example client version 8.36 will store its cache in ~/.chembl_ws_client__0.8.36.sqlite.

You have two options:
1. Find the file and delete in manually.
2. run `[sudo] pip install -U chembl_webresource_client`

The second option is recommended. With every chembl release we also release new versions of our software, including the client. The new client will have empty cache so you will see new data immediately.

You can always switch off cache completely by adding this code to the top of your script:

    from chembl_webresource_client.settings import Settings
    Settings.Instance().CACHING = False

**Comment by izharw** [comment]
Hi Michal,

I don't think its the cache. As I wrote in before I am using the latest
version (8.38) and removed all cache files. Just to be safe I've disabled
the cache as you suggested but I'm still getting back 11019 instead of the
expected 11224 targets (https://wwwdev.ebi.ac.uk/chembl/api/data/target).

Are you getting the right number of targets when running the script?

Thanks,
Izzy

**Comment by mnowotka** [comment]
Hi Izzy,

Thank you for reporting that. This is now fixed.

Now please let me explain what happened. Currently we maintain two versions of web services: 1.x and 2.x. The
