### ISSUE TITLE
link github from pypi

### ISSUE THREAD

**Issue by apierleoni** [chembl/chembl_webresource_client#16]
Hi there, 
Is there any documentation available except the blog post?
Would be nice to have a link from pypi to the github repo.
Cheers

**Comment by mnowotka** [comment]
Hi,

Yes, there is an Jupyter notebook: https://github.com/chembl/mychembl/blob/master/ipython_notebooks/09_myChEMBL_web_services.ipynb and a file with tests that cover all possible use cases: https://github.com/chembl/chembl_webresource_client/blob/master/chembl_webresource_client/tests.py

Apart from this, not much I'm afraid and for the next release I'm planning to add extensive readthedocs powered documentation. I'll keep this issue opened until this is properly solved.

**Comment by mnowotka** [comment]
Link to GitHub is now in PyPI: https://pypi.python.org/pypi/chembl_webresource_client/0.9.12.
I also extended a readme.rst with documentation.
