### ISSUE TITLE
Example usage?

### ISSUE THREAD

**Issue by avilella** [chembl/chembl_webresource_client#17]
Hi,

Are there examples of the usage of this python client?

E.g. query: approved drugs for lung cancer

**Comment by mnowotka** [comment]
Hi,

Yes, there is a Jupyther (Ipython) notebook comparing the client and making raw API requests:

https://github.com/chembl/mychembl/blob/master/ipython_notebooks/09_myChEMBL_web_services.ipynb

Also we have a very big collection of examples in the test file of the package (every endpoint is covered):
https://github.com/chembl/chembl_webresource_client/blob/master/chembl_webresource_client/tests.py

For your particular example, you should just query the 'drug_indications' endpoint (https://www.ebi.ac.uk/chembl/api/data/drug_indication.json). You can for example apply 'lung' filter like this: https://www.ebi.ac.uk/chembl/api/data/drug_indication.json?efo_term__icontains=lung

For Python client, you would write the following code:

    from chembl_webresource_client.new_client import new_client
    drug_indication = new_client.drug_indication
    molecules = new_client.molecule

    lung_cancer_ind = drug_indication.filter(efo_term__icontains="LUNG CARCINOMA")
    lung_cancer_mols = molecules.filter(molecule_chembl_id__in=[x['molecule_chembl_id'] for x in lung_cancer_ind])

Now the `lung_cancer_mols` variable contains a collection of 180 molecules related to the lung cancer.

**PLEASE NOTE** that this is just an example. In practice, you can see that querying for "LUNG CARCINOMA" will return only a part of relevant results. Another popular efo term is '"CARCINOMA, NON-SMALL-CELL LUNG"' and this won't be returned by the query in the example so you may want to extend it but now you know the gist.

If you have any other questions, please let me know.

**Comment by mnowotka** [comment]
I added documentation to the homepage of this repository. Your example is included.
