### ISSUE TITLE
Searching by synonym ?

### ISSUE THREAD

**Issue by i-shah** [chembl/chembl_webresource_client#19]
Is searching molecules / targets by synonyms supported ? If so, can you provide sample usage ? 

Thanks

**Comment by mnowotka** [comment]
Hi, 
Yes, of course this is supported. For molecules:

    from chembl_webresource_client.new_client import new_client
    molecule = new_client.molecule
    molecule.set_format('json')
    res = molecule.search('viagra')

For targets:

    from chembl_webresource_client.new_client import new_client
    target = new_client.target
    target.set_format('json')
    res = target.search('lipoxygenase')

For more advanced examples, please take a look at tests file: https://github.com/chembl/chembl_webresource_client/blob/master/chembl_webresource_client/tests.py

**Comment by i-shah** [comment]
Thank you  ! I've been looking at the REST API and trying to figure out how to filter based on the molecule_synonyms/molecule_synonym

**Comment by mnowotka** [comment]
You can do that as well:

    target = new_client.target
    gene_name = 'GABRB2'
    targets_for_gene = target.filter(target_components__target_component_synonyms__component_synonym__icontains=gene_name)

or shorter:

    shortcut = target.filter(target_synonym__icontains=gene_name)

The difference is that the 'search' method uses solr index so it's faster. When you are using 'filter' you have to know exactly where you want to search and it can be slower.

**Comment by i-shah** [comment]
Much rather use the solr index. Out of curiosity though, how would you search for molecule synonyms using a filter ?

**Comment by mnowotka** [comment]
Since a single molecule may have multiple synonyms (one to many relation) and there is no separate endpoint for synonyms this is not possible to do directly apply such a filter on the molecule entity. This is (one of the reasons) why we exposed another endpoint called 'drug': https://www.ebi.ac.uk/chembl/api/data/drug.json. But please note it only contains approved drugs (max_phase=4).

Example of searching for synonym using URL:
https://www.ebi.ac.uk/chembl/api/data/drug.json?synonyms__icontains=prazosin

and the client:

    drug = new_client.drug
    res =  drug.filter(synonyms__icontains="prazosin")

For a general synonym search across all ChEMBL molecules, the solr based 'search' method is the only option though.

**Comment by mnowotka** [comment]
Hi,

I'm closing this issue now but feel free to reopen if you have some more questions about this topic. For other questions, please create a new issue.

**Comment by i-shah** [comment]
Thanks - appreciate the help

**Comment by BJWiley233** [comment]
I just downloaded the conda package from [here](https://anaconda.org/chembl/chembl_webresource_client).  When I run:
`target.filter(target_components__target_component_synonyms__component_synonym__icontains=gene_name)`
or
`target.filter(target_synonym__icontains=gene_name)`
I get

`TypeError: 'NoneType' object cannot be interpreted as an integer`

**Comment by RetrosynthesisAI** [comment]
How should I alter the below function to retrieve the ChEMBL IDS of multiple molecule synonyms?

results = molecule.filter(molecule_synonyms__molecule_synonym__iexact='aspirin').only('molecule_chembl_id')

**Comment by RetrosynthesisAI** [comment]
Also the following code is not working, can you send a working version?

from chembl_webresource_client.new_client import new_client
from IPython.display import display, Image
chembl_id=('CHEMBL1')
i = Image(new_client.image.get(chembl_id))
display(i)
