### ISSUE TITLE
sdf file output error

### ISSUE THREAD

**Issue by greatlse** [chembl/chembl_webresource_client#20]
In [5]: with open('mols_2D.sdf', 'w') as output:
   ...:     for mol in mols:
   ...:         output.write(mol)
   ...:         output.write('$$$$\n')
   ...:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-bcd527644b1a> in <module>()
      1 with open('mols_2D.sdf', 'w') as output:
      2     for mol in mols:
----> 3         output.write(mol)
      4         output.write('$$$$\n')
      5

TypeError: expected a string or other character buffer object

**Comment by mnowotka** [comment]
Hi,

I need some more details. Can you please show me the full code and your system configuration (operating system, python version, installed packages)?

**Comment by greatlse** [comment]
OK，the OS of my PC is MAC-OS, and the python version is 2.7.12, Anaconda 4.2.0 (x64). the full code:

from chembl_webresource_client.new_client import new_client
molecule = new_client.molecule
molecule.set_format('sdf')
mols= molecule.filter(max_phase=4)
with open('mols_2D.sdf', 'w') as output:
    for mol in mols:
        output.write(mol)
        output.write('$$$$\n')

**Comment by mnowotka** [comment]
The reason you see this issue is because some of the molecules you selected, don't have a structure defined and you need to add additional condition to check that:

    from chembl_webresource_client.new_client import new_client
    molecule = new_client.molecule
    molecule.set_format('sdf')
    mols= molecule.filter(max_phase=4)
    with open('mols_2D.sdf', 'w') as output:
        for mol in mols:
            if mol:
                output.write(mol)
                output.write('$$$$\n')
