### ISSUE TITLE
possibility to do BLAST search

### ISSUE THREAD

**Issue by MKorablyov** [chembl/chembl_webresource_client#23]
Hello !

I am trying to retrieve a binding data for a small set of ~300 proteins of interest (retrieve all molecules for each of the proteins). ChEMBL has a possibility to do the BLAST search. I could not find it in the python API. Which way would you recommend ?

Thank you,

**Comment by mnowotka** [comment]
Yes, currently the API does not allow this functionality but I agree this is a good idea to add. I will mark this issue as enhancement and it will be closed once this is implemented so you should be notified when done.

**Comment by eloyfelix** [comment]
blast search on ChEMBL can be either done via ChEMBL's interface and EBI's Blast interface: https://www.ebi.ac.uk/Tools/sss/ncbiblast/
