### ISSUE TITLE
Some print statements left in that print to console.

### ISSUE THREAD

**Issue by Superraptor** [chembl/chembl_webresource_client#26]
I noticed that in the file `url_query.py` lines 290, 291, 292, 296, 297, and 298 print to the console by default. They don't appear to be necessary for function so perhaps adding a "verbose" option would be an interesting idea to suppress the print statements?

(Not necessarily an issue, just something I noticed)

**Comment by mnowotka** [comment]
Thanks, this actually is an issue since there is a logging mechanism in place so direct prints should be avaided. I will have a look.

**Comment by mnowotka** [comment]
I guess this is solved in the lastest version, I have a proof: https://github.com/chembl/chembl_webresource_client/search?utf8=%E2%9C%93&q=print&type=
