### ISSUE TITLE
Improving time turnaround for activity requests

### ISSUE THREAD

**Issue by spadavec** [chembl/chembl_webresource_client#30]
Hello 

Is there a way to improve the time it takes to retrieve activities against a target? The relevant code I'm using: 

```
for x in chembl_ids:
        if x not in existing_files:
                print("Checking CHEMBL id {}".format(x))
                res = activity.filter(target_chembl_id='{}'.format(x), relation='=', assay_type='B', standard_type="IC50")

                for sub in res:
                        if sub['parent_molecule_chembl_id'] and sub['canonical_smiles'] and sub['standard_value'] is not None:
                                ids.append(str(sub['parent_molecule_chembl_id']))
                                smiles.append(str(sub['canonical_smiles']))
                                ic50.append(float(sub['standard_value']))
```

Currently, it takes ~2 minutes and 45 seconds per ID/request--and given that I want to pull ~5000 targets, I'm hoping to improve that time :) Is there a ```SETTINGS``` that decreases ping time?

**Comment by mnowotka** [comment]
Hi,
This week I'm working on improving the speed so I'm happy to have a look at your example and experiment with different settings both on the client and server side. Can you please give a list of ~5k targets that give take you 2m45s to retrive activities?

**Comment by spadavec** [comment]
It appears that I goofed, and the slow part isn't the data retrieval, but the conversion/looping-through the list of dicts to just a list of lists of the relevant properties: 

```
for x in chembl_ids:
    if x not in existing_files:
        print("Checking CHEMBL id {}".format(x))
        res = activity.filter(target_chembl_id='{}'.format(x), relation='=', assay_type='B', standard_type="IC50")
        print("Data retrieved")

        for i,z in enumerate(res):
            if z['parent_molecule_chembl_id'] and z['canonical_smiles'] and z['standard_value'] is not None:
                temp.append([str(z['parent_molecule_chembl_id']), str(z['canonical_smiles']), float(z['standard_value'])])

        write_csv(x, temp)
```

**Comment by mnowotka** [comment]
OK, in that case is there anything I can help you here?

**Comment by mnowotka** [comment]
BTW: if you just rerun your script and noticed it's much faster it can because now the results are cached on the client side so you may concider clearing cache or configuring the client not to use the cache during profiling.

**Comment by spadavec** [comment]
Ah, thanks for the clarification. Didn't know things were getting cached on our side--it still seems that that bulk of the time is in processing of the dict being returned, so I'll close this out!

**Comment by mnowotka** [comment]
No worries, I'm still optimising the API performance, next week it should work smoother but don't expect any dramatic improvements.
