### ISSUE TITLE
Downloading bioactivities for cell lines

### ISSUE THREAD

**Issue by spadavec** [chembl/chembl_webresource_client#32]
I'd like to download all the GI50/EC50 data for a particular cell line (e.g. [CHEMBL3308372](https://www.ebi.ac.uk/chembl/cell/inspect/CHEMBL3308372)), but using the standard method doesn't seem to work: 
 
```
activity = new_client.activity
for x in chembl_ids:
    res = activity.filter(target_chembl_id='{}'.format(x), assay_type='F', standard_type="EC50", standard_value__isnull=False
```

This `res` seems to return a dataframe of celllines, and not the bioactivities against that cell line. Is there a better way to approach this?

**Comment by spadavec** [comment]
The issue here is that the `target_chembl_id` needs to be changed to `cell_chembl_id`, and the rest will work out. 

Closing.

**Comment by mnowotka** [comment]
Please note, that the `activitiy` enpoint (https://www.ebi.ac.uk/chembl/api/data/activity.json) doens't have a `cell_chembl_id` field. This is why this filter gets (silently) ignored so it's equivalent to the following:

    res = activities.filter(assay_type='F',standard_type="EC50", standard_value__isnull=False)

**Comment by spadavec** [comment]
Sorry if I'm not understanding properly, but is it then not possible to download activities against a cell line? If you try to use `target_chembl_id` and filter for functional assays and a specific standard type, it will return an empty list.

**Comment by mnowotka** [comment]
Yes, it's not possible. You can filter the `assay` endpoint using `cell_cehmbl_id` filter and then retrive all activities with the corresponding assays.
