### ISSUE TITLE
fail to load molecule by name from molecule.search()

### ISSUE THREAD

**Issue by fabricecarles** [chembl/chembl_webresource_client#34]
Hi,
In January 2018, when I run the following code I get some results.

```
from chembl_webresource_client.new_client import new_client
molecule = new_client.molecule
res = molecule.search('aspirin')
```

Now the res list is empty !

Did you have an idea ? 

PS: For viagra there is two results ;)

Thanks

**Comment by juanfmx2** [comment]
Hi @fabricecarles. Thanks, for noticing, one of the servers was down. It is now up and running, you should be able to get results for your query.

**Comment by fabricecarles** [comment]
Thanks, it work well now, I close the isue

**Comment by soerendip** [comment]
Is the server down again?
molecule.search('aztreonam') returns nothing.
