### ISSUE TITLE
Filtering with confidence score

### ISSUE THREAD

**Issue by ggerogiokas** [chembl/chembl_webresource_client#35]
Hi, 

I am unaware if it is possible to filter substructure results with a confidence score?
Do you get that as an option somewhere?

Thanks,
George

**Comment by juanfmx2** [comment]
Hi @ggerogiokas,

Unfortunately, I don't think the substructure algorithm provides a confidence score like the similarity endpoint does.  However, you could use other properties of the molecule to filter the results like the molecular weight:

https://www.ebi.ac.uk/chembl/api/data/substructure/C1%3DCC%3DC(C%3DC1)C1C%3DCC%3DCC%3D1C1C%3DCC%3DCC%3D1.json?molecule_properties__full_mwt__gte=250&molecule_properties__full_mwt__lt=300

**molecule_properties__full_mwt__gte=250&molecule_properties__full_mwt__lt=300**

This filters out of all the substructure results for C1=CC=C(C=C1)C1C=CC=CC=1C1C=CC=CC=1 that have a molecular weight greater or equal to 250 and less than 300.

You can use other properties of the molecule document to filter like:
molecule_properties__aromatic_rings or molecule_properties__alogp

Finally, you can find more documentation here:
https://www.ebi.ac.uk/chembl/ws

Hope this helps!
Juan

**Comment by ggerogiokas** [comment]
Hi Juan,

Thanks for the advice I was specifically thinking about the assay confidence score present in Chembl.  I won't only substructure hits who are found in high confidence assays.

Thanks,
George

**Comment by juanfmx2** [comment]
Hi @ggerogiokas,

Unfortunately, it is not possible at this moment. However, we might consider using it in a future release depending on the performance of te additional join with the assay table.

Thanks,
Juan
