### ISSUE TITLE
Limit in search similarity

### ISSUE THREAD

**Issue by cocodalaska** [chembl/chembl_webresource_client#36]
Hello, is there a possibility to put a limit during the search of a similarity using the example : 

from chembl_webresource_client.new_client import new_client
similarity = new_client.similarity
res = similarity.filter(smiles="CO[C@@H](CCC#C\C=C/CCCC(C)CCCCC=C)C(=O)", similarity=70)

The idea is to stop the search at 5 compounds and gain time. 
Thanks, 
Colin

**Comment by fabricecarles** [comment]
Indeed, I think it could be very useful. 
Is it possible to limit number of rows results ?   
Fabrice

**Comment by eloyfelix** [comment]
Similarity search is much faster than before since it now uses FPSim2 instead of a database cartridge. https://github.com/chembl/FPSim2

FPSim2 is RDKit based and the example molecule seems to be failing to parse with it:

```python
from rdkit import Chem

mol = Chem.MolFromSmiles("COC@@HC(=O)")
```
