### ISSUE TITLE
Missing link to Travis-CI on home page

### ISSUE THREAD

**Issue by cthoyt** [chembl/chembl_webresource_client#41]
It's much easier to get quick feedback as a user on the stability of the project if there's a link/badge on the home page. 

Markdown:

```markdown
[![Build Status](https://travis-ci.org/chembl/chembl_webresource_client.svg?branch=master)](https://travis-ci.org/chembl/chembl_webresource_client)
```

RST:

```restructuredtext
.. image:: https://travis-ci.org/chembl/chembl_webresource_client.svg?branch=master
    :target: https://travis-ci.org/chembl/chembl_webresource_client
```

**Comment by cthoyt** [comment]
Oh sorry, it seems that it's at the bottom. I would highly suggest putting it prominently at the top along with the other badges.

**Comment by juanfmx2** [comment]
Hi @cthoyt thanks for the suggestion. I'm aware this project have issues with the newer versions of python. I'll try to find sometime to fix most of the issues this package is experiencing right now.

**Comment by cthoyt** [comment]
@jmarinllao just sent a pull request (#43) to address the issues with the async keyword, but it looks like there are still some outstanding problems with greenlets and gevent. We'd be happy to help however we can, but neither of us are familiar with these libraries. For now we'll be happy to be your test subjects!

**Comment by juanfmx2** [comment]
thanks @cthoyt and @jmarinllao, I'm seriously considering getting rid of those libraries and use native threads or processes from python, as it seems the monkey patch thing that they provide is quite unstable in the newer releases. I'll keep you updated!
