### ISSUE TITLE
Conda install on python 3.6 fails (pip works though)

### ISSUE THREAD

**Issue by ankitvgupta** [chembl/chembl_webresource_client#44]
When I run the conda install line in a python 3.6 conda environment, I get the following error:

```
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - chembl_webresource_client -> easydict -> python >=2.7,<2.8.0a0
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

Looks like the requirements are set to only include python 2. Since this library supports python 3, it's probably best to change that requirement.

**Comment by eloyfelix** [comment]
please install the new version using pip:

```
pip install chembl-webresource-client
```

we dropped py2 support as Python Foundation is also doing it.
