### ISSUE TITLE
Warnings generated with Python 3.6

### ISSUE THREAD

**Issue by PatWalters** [chembl/chembl_webresource_client#46]
There seem to be some issues with Monkey Patching in gevent 

/Users/pwalters/anaconda/envs/rdkit_2018_03/lib/python3.6/site-packages/grequests.py:22: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.contrib.pyopenssl (/Users/pwalters/anaconda/envs/rdkit_2018_03/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py)', 'urllib3.util (/Users/pwalters/anaconda/envs/rdkit_2018_03/lib/python3.6/site-packages/urllib3/util/__init__.py)'].
  curious_george.patch_all(thread=False, select=False)

**Comment by jonjoncardoso** [comment]
I can confirm, I'm seeing the same warnings

**Comment by KevinHock** [comment]
Who is curious george?

**Comment by eloyfelix** [comment]
This issue is already fixed in master as we are dropping old webservices resources (TargetResource, CompoundResource) and Py2 comptatibility.
