### ISSUE TITLE
cannot access TargetResource

### ISSUE THREAD

**Issue by zeromtmu** [chembl/chembl_webresource_client#47]
I try to access TargetResource via chembl_webresource_client but some error occurs. 

<img width="1031" alt="screen shot 2561-09-17 at 11 11 24" src="https://user-images.githubusercontent.com/11990772/45606009-d73a7680-ba6b-11e8-9244-44bb0563e58f.png">

**Comment by eloyfelix** [comment]
TargetResource and CompoundResource are deprecated as we shut down the endpoints that served them a while ago. You should instead use molecule and target using "new_client" object as shown on the readme file.

```
from chembl_webresource_client.new_client import new_client

molecule = new_client.molecule
target = new_client.target
```
