### ISSUE TITLE
No connection without error message.

### ISSUE THREAD

**Issue by soerendip42** [chembl/chembl_webresource_client#5]
Hi,

thank you for this client its really helpful software!
The following comes up, when I initiate the client from an activated anaconda-environment. The connection works, when the environment is deactivated. It seems there are certain dependencies not fullfilled, however the error message does not say what exactly goes wrong. Are you aware of specific python packages (environment conditions in general)  to run the chembl client??

here is what happens ----->

import chembl_webresource_client as cwc
assays    = cwc.AssayResource()
assays.status()

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-75df1099e355> in <module>()
      1 import chembl_webresource_client as cwc
      2 assays    = cwc.AssayResource()
----> 3 targets.status()

/home/swacker/Programme/anaconda/lib/python2.7/site-packages/chembl_webresource_client/web_resource.pyc in status(self)
     95     def status(self):
     96         service = self.get_service()
---> 97         if not 'status' in service:
     98             return False
     99         return service['status'] == 'UP'

TypeError: argument of type 'NoneType' is not iterable

**Comment by mnowotka** [comment]
Hi @teramind, thank you for using our client. Can you check this ticket: https://github.com/chembl/chembl_webresource_client/issues/1, I think it describes your problem. This boils down to incompatibility of python 2.7.9, which breaks urllib3 (https://github.com/shazow/urllib3/issues/482) and gevent (https://github.com/gevent/gevent/issues/477).

There are basically two solutions:

1. Change your python version to 2.7.6 or lower for example by doing:

    ```
    conda create -q -n py276 python=2.7.6 
    ```
You can take a look at how we configure our environment to perform travis tests (https://github.com/chembl/chembl_webresource_client/blob/master/.travis.yml).

2. Use new part of the client called `new_client`. It implements django-like interface and is generally more flexible than older client you are currently using. It doesn't use gevent anymore so there shouldn't be any compatibility issues. One example of using it is here: https://gist.github.com/mnowotka/c0fff4f8560c17e0b473, lots of other examples are covered in tests (https://github.com/chembl/chembl_webresource_client/blob/master/chembl_webresource_client/tests.py). There will be a blog post next week, which will hopefully cover all the important features of the new client. If you have any specific questions, you can ask them here or contact us via email: chembl-help@ebi.ac.uk.

**Comment by teramind** [comment]
This,
> from chembl_webresource_client.new_client import new_client  

gives me 

TypeError                                 Traceback (most recent call last)
<ipython-input-3-20c3d0f96fa5> in <module>()
----> 1 from chembl_webresource_client.new_client import new_client
      2 

/home/swacker/Programme/anaconda/lib/python2.7/site-packages/chembl_webresource_client/new_client.py in <module>()
     61 #-----------------------------------------------------------------------------------------------------------------------
     62 
---> 63 new_client = client_from_url(Settings.Instance().NEW_CLIENT_URL + '/spore')
     64 
     65 #-----------------------------------------------------------------------------------------------------------------------

/home/swacker/Programme/anaconda/lib/python2.7/site-packages/chembl_webresource_client/new_client.py in client_from_url(url, base_url)
     25 
     26     """
---> 27     res = requests.get(url)
     28     if not res.ok:
     29         raise Exception('Error getting schema from url %s with status %s and msg %s' % (url, res.status_code, res.text))

/home/swacker/Programme/anaconda/lib/python2.7/site-packages/requests/api.pyc in get(url, **kwargs)
     63 
     64     kwargs.setdefault('allow_redirects', True)
---> 65     return request('get', url, **kwargs)
     66 
     67 

/home/swacker/Programme/anaconda/lib/python2.7/site-packages/requests/api.pyc in request(method, url, **kwargs)
     47 
     48     session = sessions.Session()
---> 49     response = session.request(method=method, url=url, **kwargs)
     50     # By explicitly closing the session, we avoid leaving sockets open which
     51     # can trigger a ResourceWarning in some cases, and look like a memory leak

/home/swacker/Programme/anaconda/lib/python2.7/site-packages/requests/sessions.pyc in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    459         }
    460         send_kwargs.update(settings)
--> 461         resp = self.send(prep, **send_kwargs)
    462 
    463         return resp

/home/swacker/Programme/anaconda/lib/python2.7/site-packages/requests/sessions.pyc in send(self, request, **kwargs)
    571 
    572         # Send the request
--> 573         r = adapter.send(request, **kwargs)
    574 
    575         # Total elapsed time of the request (approximately)

/home/swacker/Programme/anaconda/lib/python2.7/site-packages/requests/adapters.pyc in send(self, request, stream, timeout, verify, cert, proxies)
    368                     decode_content=False,
    369                     retries=self.max_retries,
--> 370                     timeout=timeout
    371                 )
    372 

/home/swacker/Programme/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.pyc in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, **response_kw)
    542             httplib_response = self._make_request(conn, method, url,
    543                                                   timeout=timeout_obj,
--> 544                                                   body=body, headers=headers)
    545 
    546             # If we're going to release the connection in ``finally:``, then

/home/swacker/Programme/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.pyc in _make_request(self, conn, method, url, timeout, **httplib_request_kw)
    339         # Trigger any extra validation we need to do.
    340         try:
--> 341             self._validate_conn(conn)
    342         except (SocketTimeout, BaseSSLError) as e:
    343             # Py2 raises this as a BaseSSLError, Py3 raises it as socket timeout.

/home/swacker/Programme/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.pyc in _validate_conn(self, conn)
    760         # Force connect early to allow us to validate the connection.
    761         if not getattr(conn, 'sock', None):  # AppEngine might not have  `.sock`
--> 762             conn.connect()
    763 
    764         if not conn.is_verified:

/home/swacker/Programme/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.pyc in connect(self)
    236                                     ca_certs=self.ca_certs,
    237                                     server_hostname=hostname,
--> 238                                     ssl_version=resolved_ssl_version)
    239 
    240         if self.assert_fingerprint:

/home/swacker/Programme/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.pyc in ssl_wrap_socket(sock, keyfile, certfile, cert_reqs, ca_certs, server_hostname, ssl_version, ciphers, ssl_context)
    254         context.load_cert_chain(certfile, keyfile)
    255     if HAS_SNI:  # Platform-specific: OpenSSL with enabled SNI
--> 256         return context.wrap_socket(sock, server_hostname=server_hostname)
    257     return context.wrap_socket(sock)

/home/swacker/Programme/anaconda/envs/env1/lib/python2.7/ssl.pyc in wrap_socket(self, sock, server_side, do_handshake_on_connect, suppress_ragged_eofs, server_hostname)
    348                          suppress_ragged_eofs=suppress_ragged_eofs,
    349                          server_hostname=server_hostname,
--> 350                          _context=self)
    351 
    352     def set_npn_protocols(self, npn_protocols):

TypeError: __init__() got an unexpected keyword argument 'server_hostname'

**Comment by mnowotka** [comment]
OK, in that case, I think that currently only the first solution (changing python version) is valid. Can you check, which python version are you currently using?

**Comment by teramind** [comment]
OK, the reason why my old scripts did not work was because some names changed.
E.g. chemblId to chemblid. 
I appreciate that. 
I found one inconsistency with the old client:
>compounds = cwc.CompoundResource()
>compounds.get()   

still returns chemblId instead of chemblid.
