### ISSUE TITLE
Pickle error Python2/3 compatibility

### ISSUE THREAD

**Issue by danielSoler93** [chembl/chembl_webresource_client#58]
# Description

When installing and running chembl_webresource_client for python2.7
when doing unichem.structure(name,1) it goes to the request_cache package 
and this fails to unpickle something along the process. Would it be possible
to add a protocol=2 if there's ValueError?

# Error    

def __getitem__(self, key):
>       return pickle.loads(bytes(super(DbPickleDict, self).__getitem__(key)))
E       ValueError: unsupported pickle protocol: 3

../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/lib/python2.7/site-packages/requests_cache/backends/storage/dbdict.py:163: ValueError

# Reproduce Error

From https://github.com/danielSoler93/modtox  git clone and conda-build conda_recipe/ this will run some test and fail at this point

Thanks,

Dani

**Comment by eloyfelix** [comment]
Hi Daniel, 
since Python2 support will end soon (https://www.python.org/doc/sunset-python-2/) we also decided to drop Py2 compatibility on this client. This will allow us to keep the library better updated for newer Python versions. Sorry for any inconvenience.
