### ISSUE TITLE
Old chembl_webresource_client.sqlite incompatible with new version

### ISSUE THREAD

**Issue by samoturk** [chembl/chembl_webresource_client#6]
It seems that old chembl_webresource_client.sqlite can be incompatible with new version. I updated chembl_webresource_client from 07. to current (0.8.4) and experienced some weird behaviour. When I deleted the sqlite file everything started working normally.  
Maybe it would be useful if there would be a warning notifying user that old sqlite db might be incompatible?

**Comment by mnowotka** [comment]
Hi @samoturk !
Yes, definitely, thanks for reporting this. We are currently on holidays (and hence such a long response time) but this will be fixed soon.

**Comment by mnowotka** [comment]
This is now fixed. New versions of the client by default write cache to the hidden file in the home directory:  ~/.chembl_ws_client_<version>.sqlite so the current directory is not polluted anymore and new version uses different file.
