### ISSUE TITLE
Metabolism information

### ISSUE THREAD

**Issue by BartoszBartmanski** [chembl/chembl_webresource_client#70]
Is there a way for this client to return metabolism information, as the web interface does? For example, when I search for tacrolimus, I get all the metabolites for the given molecule in a grapth (shown below) and I was wondering whether it would be possible to get at least chembl IDs for the metabolites when using chembl wrc.

![image](https://user-images.githubusercontent.com/16625050/71592164-17215200-2b27-11ea-9948-5198421af9f9.png)

**Comment by dafwb** [comment]
Did you find any solution for that?

**Comment by BartoszBartmanski** [comment]
Unfortunately no

**Comment by juanfmx2** [comment]
Hi @BartoszBartmanski, Sorry we missed your question before. There is a 'metabolism' endpoint in the web services. You can use it like this:

https://www.ebi.ac.uk/chembl/api/data/metabolism.json?drug_chembl_id=CHEMBL269732

Please let me know if you have any questions.

**Comment by eloyfelix** [comment]
you can also use the client:

```python
from chembl_webresource_client.new_client import new_client

metabolism = new_client.metabolism
res = metabolism.filter(drug_chembl_id="CHEMBL269732")
```
