### ISSUE TITLE
'component_synonym' field does not support relations.

### ISSUE THREAD

**Issue by sayonidas** [chembl/chembl_webresource_client#76]
Hi, 

I updated the chembl package today that fixed #71 
However, I am now getting a new error:

`The 'component_synonym' field does not support relations.`

for the following line of code:

`full_targets = new_client.target.filter(target_synonym__iexact=gene_name).only('target_chembl_id', 'target_type', 'organism')`

Please advise how to fix this. Have any of the API endpoints/usage been updated in the new release ?

**Comment by gedeck** [comment]
I get a similar error for:
```
    molecule = new_client.molecule
    results = molecule.filter(molecule_synonyms__molecule_synonym__icontains=identifier)
```
This stopped working on March 3rd.

**Comment by eloyfelix** [comment]
Thanks for reporting.

Some changes in our webservices https://github.com/chembl/chembl_webservices_py3 affected those functionalities. We are now looking into it.

**Comment by eloyfelix** [comment]
I'm closing this issue here as I opened one in the relevant repository:

https://github.com/chembl/chembl_webservices_py3/issues/5

**Comment by eloyfelix** [comment]
FYI, the issue was already fixed and deployed in our webservices so your queries should be working again.
