### ISSUE TITLE
Max retries exceeded with url: /chembl/api/data/molecule/CHEMBL3990002 

### ISSUE THREAD

**Issue by Vanisri-Chepuri** [chembl/chembl_webresource_client#77]
i have updated 0.10.1 version. getting a new issue with few Chebi IDs which is mentioned below. Please do needful.

*************HTTPSConnectionPool(host='www.ebi.ac.uk', port=443): Max retries exceeded with url: /chembl/api/data/molecule/CHEMBL3990002 (Caused by ResponseError('too many 404 error responses',))

**Comment by eloyfelix** [comment]
CHEMBL3990002 doesn't exist anymore in chembl26. We probably should give a clearer message though.

https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL3990002/
