### ISSUE TITLE
Problems running "from chembl_webresource_client.new_client import new_client"

### ISSUE THREAD

**Issue by apinedalucena** [chembl/chembl_webresource_client#79]
Hi,

I am trying to run the task underline in the subject of the issue but I can´t get it working. I would like to run the tutorial of TeachOpenCADD, so I have created an environment (teachopencadd) with the different packages, including "chembl_webresource_client", that are required to run the tutorials. However, it does not work. Please, see attached pictures: (i) displaying the packages that have been installed; (ii) the errors I get when trying the command running. 

Look forward to finding a solution!

Best,

Antonio
<img width="1012" alt="Screen Shot 2020-03-22 at 17 46 50" src="https://user-images.githubusercontent.com/57092174/77255385-4dbec280-6c67-11ea-892f-3ec49c264ff1.png">
<img width="1010" alt="Screen Shot 2020-03-22 at 17 47 29" src="https://user-images.githubusercontent.com/57092174/77255392-58795780-6c67-11ea-9d95-fce610e5ad78.png">

**Comment by eloyfelix** [comment]
Hi, this issue should disappear after upgrading to version 0.10.1

**Comment by apinedalucena** [comment]
It does work! Thank you so much!
