### ISSUE TITLE
Clinical trial phase

### ISSUE THREAD

**Issue by samoturk** [chembl/chembl_webresource_client#8]
I'm having trouble figuring out how would one get a clinical trial phase of a compound via chembl_webresource_client. Is this possible?

**Comment by mnowotka** [comment]
Yes, you have to use new client:

    from chembl_webresource_client.new_client import new_client as nc

and then if you select a single compound you will find `max_phase` field:

    nc.molecule.get('CHEMBL25')
    >>> {u'max_phase': 4,...}

you can even filter by max_phase for example:

    approved_drugs = nc.molecule.filter(max_phase=4).order_by('molecule_chembl_id')
    # do something useful....
    drug_ids = [drug['chembl_id'] for drug in approved_drugs]

**Comment by samoturk** [comment]
Thanks! I wasn't even aware there is a new client..

**Comment by mnowotka** [comment]
I know, blog post is coming soon...

**Comment by samoturk** [comment]
Maybe a talktorial at RDKit UGM? :)

**Comment by mnowotka** [comment]
I wish to but I UGM date collides with my personal plans :(
