### ISSUE TITLE
ID lookup - connection errors?

### ISSUE THREAD

**Issue by sigven** [chembl/chembl_webresource_client#85]
Hi,

I am using the webservice to search for compounds by name, e.g. 

`https://www.ebi.ac.uk/chembl/api/data/chembl_id_lookup/search?format=json&q=ammonium%20trichlorotellurate`

When I loop through a list of names, I experience http errors for queries now and then, apparently in an unpredictable manner. Is there any recent update that might explain this? It usually works without problem.

regards,
Sigve

**Comment by eloyfelix** [comment]
sorry for the delayed reply. We possibly experienced some infrastructure related issues back then. It is working fine now.
