### ISSUE TITLE
Can't import new_client from chembl_webresource_client.new_client

### ISSUE THREAD

**Issue by raysteven** [chembl/chembl_webresource_client#97]
When I tried to execute:

`from chembl_webresource_client.new_client import new_client`

this error comes out:

> ImportError                               Traceback (most recent call last)
<ipython-input-2-154789b4cb6b> in <module>()
      1 # Import necessary libraries
      2 import pandas as pd
----> 3 from chembl_webresource_client.new_client import new_client

> 4 frames
/usr/local/lib/python3.7/dist-packages/chembl_webresource_client/cache.py in <module>()
      1 __author__ = 'mnowotka'
      2 
> ----> 3 from requests_cache.backends.base import BaseCache, hashlib, _to_bytes
      4 
      5 def create_key(self, request):

> ImportError: cannot import name 'hashlib' from 'requests_cache.backends.base' (/usr/local/lib/python3.7/dist-packages/requests_cache/backends/base.py)

Is there a fix for this?

**Comment by eloyfelix** [comment]
same issue than #96, we'll release a new version soon

**Comment by raysteven** [comment]
@eloyfelix so it's unusable for now?
